runbot/templates/build.xml, runbot/templates/frontend.xml
Some HTML attributes were missing, and are required to ensure good
compatibility with screen readers.
The following attributes are included:
- `aria-expanded`: this should be present in all dropdown menus
- `aria-label`: this should be present in all links and buttons which
don't show text, but icons or images.
=> [FIX] runbot: Add missing HTML attributes aria-*

runbot/controllers/hook.py
Work the task from TODO comment.
This change allow use a global webhook from github based on the organization without use a configuration for each repository.
I means, you should configure a global webook for all repository from the organization:
- https://github.com/organizations/Vauxoo/settings/hooks
Instead of use a configuration for each project:
- https://github.com/Vauxoo/project1/settings/hooks
- https://github.com/Vauxoo/project2/settings/hooks
- https://github.com/Vauxoo/project3/settings/hooks
- https://github.com/Vauxoo/project4/settings/hooks
...
=> [REF] runbot: hook - Find the right repo from payload

runbot/common.py, runbot/models/build.py
When code coverage was processed the 'coverage' utility was called the
same way regardless of the Odoo version. That was the cause of two
problems:
1) In some OS packages, the 'coverage' executable was renamed to
'python-coverage' and 'python3-coverage'
2) Since version 11.0, Odoo needs python3
With this commit, the coverage module is called from python '-m'
argument and the python version is choosen from the Odoo executable
shebang.
=> [IMP] runbot: choose the python version for coverage

runbot/models/repo.py, runbot/tests/__init__.py, runbot/tests/test_subject_skip_build.py
This module skip a build based on the commit message.
Inspired by [Travis-CI#Skipping-a-build](https://docs.travis-ci.com/user/customizing-the-build#Skipping-a-build)
- If you don’t want to run a build for a particular commit for any reason, add `[ci skip]` or `[skip ci]` to the git commit message.
- Commits that have `[ci skip]` or `[skip ci]` anywhere in the commit messages are ignored by Travis CI.
- Note that in case multiple commits are pushed together, the `[skip ci]` or `[ci skip]` takes effect only if present in the commit message of the HEAD commit.
=> [REF] runbot: Skip build from commit message

runbot/controllers/frontend.py, runbot/templates/build.xml
When a reverse dependency is in testing, pending or deathrow state, there is no
icon in the depending build box.
This commit adds icons for testing, pending and deathrow states.
Also, icons are now displayed in the repository name order.
=> [IMP] runbot: add icons for reverse dependency builds

runbot/models/repo.py, runbot/tests/test_subject_skip_build.py
- Add testcase
Running the tests without the fix `ValueError: not enough values to unpack (expected 9, got 1)`
```bash
2018-05-09 19:23:55,582 11255 ERROR runbot_11_3 odoo.addons.runbot.tests.test_subject_skip_build: ERROR
2018-05-09 19:23:55,583 11255 INFO runbot_11_3 odoo.addons.runbot.tests.test_subject_skip_build: ======================================================================
2018-05-09 19:23:55,583 11255 ERROR runbot_11_3 odoo.addons.runbot.tests.test_subject_skip_build: ERROR: test_subject_skip_build (odoo.addons.runbot.tests.test_subject_skip_build.TestRunbotSkipBuild)
2018-05-09 19:23:55,583 11255 ERROR runbot_11_3 odoo.addons.runbot.tests.test_subject_skip_build: ` Test [ci skip] feature
2018-05-09 19:23:55,583 11255 ERROR runbot_11_3 …
```
=> [FIX] runbot: Fix commit body multiline

runbot/__manifest__.py, runbot/controllers/frontend.py, runbot/data/runbot_cronbuild.xml, runbot/models/__init__.py, runbot/models/branch.py, runbot/models/build.py, runbot/models/cronbuild.py, runbot/models/repo.py, runbot/security/ir.model.access.csv, runbot/templates/frontend.xml, runbot/tests/__init__.py, runbot/tests/test_cronbuild.py, runbot/views/build_views.xml, runbot/views/cronbuild_views.xml
Actually, a build in a branch is created when a new commit is found.
When a user wants to schedule a time-based build, he has to generate a
commit outside of the runbot (e.g. in a cron script).
With this commit, cron builds can be scheduled hourly, daily, weekly or  monthly with extra parameters.
=> [IMP] runbot: allow extra builds based on a cron

runbot/models/repo.py, runbot/templates/nginx.xml
When someone tries to log in an old runbot build that is not running
anymore, he lands on the runbot instance that was running the build.
Also, all the running builds are allowed on all runbot instances,
leading to the same behavior.
With this commit, only the builds that are running on the runbot
instance can be reached, others are defaulted to a 404.
=> [IMP] runbot: update nginx template

runbot/models/repo.py
When a new commit is found and a new build is created. When a user
pushes more commits in the same branch a few minutes later, it causes
more builds in testing phase, resulting in a CPU waste.
With this commit, previous builds in testing phase in non sticky
branches are killed when a new build is created.
=> [IMP] runbot: kill older builds when a new one is created

runbot/models/branch.py, runbot/templates/frontend.xml
On the frontend, the coverage is a static indication.
With this commit, this indication is now a link to the coverage details
page.
=> [IMP] runbot: add link to the latest coverage

runbot/__manifest__.py, runbot/controllers/frontend.py, runbot/models/build.py, runbot/models/repo.py, runbot/templates/dashboard.xml, runbot/templates/frontend.xml
Adding a unicode icon in the subject led to some issues. e.g. a user doesn't have any clue of what the icon really means. Also, the icon not the same everywhere, depending on the browser and the fonts installed.
With this commit, a field is added to differentiate build types. Using that information, an fa icon is displayed with the appropriate title description.
=> [FIX] runbot: add recycle icon only once

runbot/models/build.py
In a near future, Odoo will use Chrome Headless instead of phantomjs.
Chrome needs a port to listen to and it was decided that it will be
http_port + 2.
With this commit, we ensure that this port is not used by another build.
=> [IMP] runbot: skip an additional port for chrome

runbot/models/repo.py
This improves the time needed to fetch the refs from https://github.com/odoo/odoo.
Running 2 commands needs to sessions on the client and server to fetch the refs. Running both fetches in one command drastically safes time needed for the fetches.
Performance tests taken on my system indicate safed time of 2seconds per run of repo._schedule (if no refs are updated):
```
(venv) bigbear3001@wt-io-it-bigbear3001:~/Documents/workspace_odoo11/runbot/runbot/static/repo/https___github.com_odoo_odoo.git$ time bash -c 'git fetch -p origin +refs/heads/*:refs/heads/* && git fetch -p origin +refs/pulls/*:refs/pulls/*'
real    0m4,440s
user    0m0,184s
sys     0m0,083s
(venv) bigbear3001@wt-io-it-bigbear3001:~/Documents/workspace_odoo11/runbot/runbot/static/repo/https___github.com_odoo_odoo.git$ time …
```
=> [IMP] runbot: perform fetch with one git command

runbot/__manifest__.py, runbot/controllers/frontend.py, runbot/templates/branch.xml, runbot/templates/frontend.xml
The frontend view shows only the four last builds by branch, which is a
little bit small to explore builds and search for failed builds.
With this commit, a new frontend template displays a paged list of
builds for a specified branch.
=> [IMP] runbot: add a frontend template

runbot/__manifest__.py, runbot/models/branch.py, runbot/models/repo.py, runbot/views/branch_views.xml
This commit permits to prioritize a branch when scheduling builds.
It's main purpose is for the runbot_merge module. It avoids to have
staging branches as sticky and pollutes the main repo view.
Also, that branch can benefit of the autokill feature when a newer build
is found, freeing ressources for other builds.
=> [IMP] runbot: add priority field on branch

runbot/models/branch.py
This one flew under the radar because it only affects a PR when its
branch name changes.
=> [FIX] runbot: store pull_head_name on branch

runbot/templates/dashboard.xml, runbot/templates/frontend.xml
For scheduled build
While schedule can be at any time, it typically runs during the night, hence the moon
```shell
$ sed -i 's|fa-clock-o|fa-moon-o|g' runbot/*/*.xml
```
=> [IMP] runbot: replace clock by moon icon

runbot/__manifest__.py, runbot/models/branch.py, runbot/models/build.py
In the case of PR, the name contains 'refs/pull/3175', the branch_name
contains '3175' and because of the previous fix e095170f8c98, the
pull_head_name sontains something like 'blah:12.0-something'.
In that case, the _get_closest_branch_name reaches the fallback.
With this commit, the target_branch_name is stored in a new field and is
used as the fallback.
=> [REF] runbot: store the target branch name

runbot/models/build.py, runbot_cla/runbot.py
When a PR is a duplicate of a branch, only the branch CLA status are
update. The same issue for build status was fixed in commit 4f1a55da9.
With this commit, there is new method than can be used in runbot_cla.
This method updates commit given status in each repo.
=> [FIX] runbot, runbot_cla: notify each repo of cla status

runbot/container.py
When starting a container, the .odoorc|.openerp_serverrc file is not
used by the build.
With this commit, if a .odoorc or .openerp_serverrc file is found in the
home directory of the runbot user, this file is mounted read-only in the
container, allowing some customization.
=> [FIX] runbot: mount host odoorc file in the container

runbot/common.py, runbot/controllers/frontend.py, runbot/tests/__init__.py, runbot/tests/test_branch.py, runbot/tests/test_build.py, runbot/tests/test_frontend.py, runbot/tests/test_jobs.py, runbot/tests/test_repo.py
Deploying non tested code is prone to errors and leads to frustration.
With this commit, basic tests are done to avoid such a situation.
=> [IMP] runbot: add basic tests

runbot/__manifest__.py, runbot/models/branch.py, runbot/models/build.py, runbot/models/repo.py, runbot/tests/__init__.py, runbot/tests/test_branch.py, runbot/tests/test_build.py, runbot/tests/test_job_types.py, runbot/views/branch_views.xml, runbot_cla/runbot.py
On our runbot, there's no reason to build or mount tmp branches (they're where runbot_merge sets up / creates the branches it's eventually staging so there's a lot of churn none of which matters).
Also, there is little reasons to keep staging branches running after the build.
This PR adds a selection field to choose the kind of jobs wanted for the branches, that way the tmp branches can be ignored and the staging branches can be built but not keeping running.
The ability to create ignore patterns at the repo level (or somesuch) might eventually be useful, but for now it looks way overkill: new tmp branches only get defined when adding new branches/targets to runbot_merge, and it's not super problematic if we forget to blacklist one such branch, it just creates some unnecessary …
=> Support for blacklisting branches (builds-wise)

runbot/models/build.py, runbot/tests/test_build.py, runbot/tests/test_job_types.py
Since 8c73e6a it's possible to skip jobs from a build by using the
job_type field on the branch. If a branch job_type is set to 'none', the
builds are created but they stay in 'pending' state.
With this commit, the build is not even created if the 'job_type' is
'none'.
=> [FIX] runbot: prevent build creation on job_type none

runbot/models/build.py, runbot/tests/__init__.py, runbot/tests/test_jobs.py, runbot/tests/test_schedule.py
When a build reach the job30_run method, results from a previous testing
methods are computed.
With the previous commit 8c73e6a90133c8915ced619a31e48b10fb01b70d this
job can now be skipped. In that case, the results are not set.
With this commit, the results are computed in a separate method.
=> [FIX] runbot: write build results in a separate job

runbot_merge/models/pull_requests.py
The `_order` of pull requests are just the `number`.
Allow test `test_two_of_three_unready` to be reliable as both unready
PRs have the same number.
=> [IMP]: runbot_merge: sort unready PRs alphabetically

runbot/models/build.py
The docker using this database may still be alive.
=> [FIX] runbot: terminate all active queries before dropping database

runbot/models/build.py
When running the _job_10 method, a database is created with base module
alone. Tests are enabled during this job. Those tests are run again with
the _job_20 method. Moreover, even if the tests fail during _job_10,
they are not taken into account for the final result. The _job_10 method
duration is approximately 4 min.
With this commit, the tests are not enabled during _job_10.
=> [IMP] runbot: avoid running test when installing base

runbot/controllers/frontend.py
When displaying build logs, all the messages from ir_logging about this
particular build are fetched from the database.
From time to times, it happens that the number of logged messages is
really huge. Those messages lines could also contain multiple lines,
multiplying the number of row to generate in the html page.
When this happens, the process that generates the template last a long
time and ends with a MemoryError. If the end user, bored, hits the
refresh button multiple times, all the workers will be busy building
this template. In the end, all users get a Bad Gateway from nginx.
With this commit, the number of messages that will be taken into account
will be limited to 10000.
=> [FIX] runbot: limit number of log lines shown on build page

runbot/models/build.py, runbot/models/repo.py, runbot/tests/test_cron.py
When a runbot execute the cron_fetch_and_build method, a new pending
build can be created between the repo update and the scheduling.
If it happens, the runbot tries to export a hash reference the does not
exists yet.
With this commit, the repo update is done right before exporting the
repo and only if the commit hash is not found.
=> [FIX] runbot: update repo if needed before exporting

runbot/models/build.py, runbot/tests/test_build.py
When a PR is created in odoo/enterprise but without a corresponding
PR in odoo/community BUT a corresponding branch in odoo-dev/community,
the closest_branch detection fails. Moreover, the duplicate detection
fails too.
As a consequence, the PR build will probably fail because it will be
built with the default target branch that could not be suited for it.
If the branch built succeeds, it leads to inconsistent results.
With this commit, a new case is added on the _get_closests_branch_name
to handle this case.
The serever_match field also reflects the difference as this case will
be marked as 'no PR'.
When a PR also exists in odoo/community, the server_match field will be
'exact PR'. This change should not imply migration.
This commit also adds a bunch of tests to test the closests branch …
=> [FIX] runbot: find duplicate when no PR in community

runbot/controllers/frontend.py, runbot/models/build.py, runbot/templates/frontend.xml, runbot/tests/test_build.py
When searching the builds for the frontend the resulting query can last
a very long time (up to 7sec).
With this commit, the search result is strictly limited to 1000 builds
and the search string length is limited to 60 chars.
Also, the branch_id many2one field on build is set to auto_join in order
to generate a better sql query. Thanks @tbe-odoo.
=> [FIX] runbot: speedup and limit search in frontend

runbot/models/repo.py, runbot/templates/frontend.xml, runbot/tests/test_repo.py
When using a local git repo, the git name does not have colon, making
the frontend crash.
With this commit, a non-stored computed field 'short_name' is added to
compute a shortest version of the name.
=> [FIX] runbot: use a repo short name to avoid bugs in qweb template

runbot/models/repo.py, runbot/tests/test_repo.py
When some special builds are scheduled during the night, free slots on
runbot instances are used. Depending on the number of scheduled builds,
all the slots can be used. That prevents people to use the runbot for
normal builds during this time.
To mitigate the problem, the scheduled builds were postponed to the
middle of the night ... the CET night. It means that it could be morning
in India.
With this commit, a build priority is given to normal builds. On the
other hand, scheduled builds are pushed at the end of the queue.
So even if there are plenty of builds during the Belgian night, if
someone pushes a commit in between, it will be built in priority before
the scheduled pending builds.
=> [IMP] runbot: give priority to normal builds

runbot/__manifest__.py, runbot/models/__init__.py, runbot/models/branch.py, runbot/models/build.py, runbot/models/build_dependency.py, runbot/models/repo.py, runbot/security/ir.model.access.csv, runbot/templates/build.xml, runbot/tests/test_build.py, runbot/tests/test_frontend.py
Before this commit, dependencies (i.e. community commit to use when testing enterprise)
where computed at checkout, when the build was going from pending to testing state and
were not stored.
Since the duplicate detection was done at create, the get_closest_branch_name was called
in a loop for each posible duplicate candidate, then a last time at checkout. The main idea of this
pr is to store the build dependecies on build at create, making the duplicate detection
faster (especially when the build name was matching many indirect build).
The side effect of this change is that the build dependencies won't be affected if a new
commit is pushed between the build creation and the checkout. The build is fully
determined at creation. get_closest_branch is only called once per build
The duplicate …
=> [IMP] add dependencies to build

runbot/models/build.py, runbot/models/repo.py, runbot/tests/test_cron.py, runbot/tests/test_repo.py
When searching for new builds by parsing git refs, the new branches are
created as well as the pending builds in the same _find_new_commits
method.
With this commit, this behavior is splitted into two methods, that way,
it's now possible to create missing branches without creating new
builds.
=> [IMP] runbot: split branch creation and pending builds creation

runbot/models/repo.py
At the end of the _update_git method, the "git fetch" command is run.
That makes it diffcult to override to change its behavior (for example
to avoid fetching pull requests).
With this commit, the command is separated in a new small method that
can be easily overriden.
=> [IMP] runbot: use a separate method for git fetch command

runbot/models/build.py, runbot/models/res_config_settings.py
When a build exceeds the cpu limit, it is simply killed by the kernel.
As a safeguard the "Initiating shutdown." sentence should be searched
in the log file, and the build marked as "ko" if not found.
Unfortunateley, there is no period (.) at the end of the sentence in the
Odoo logs (see: https://github.com/odoo/odoo/blob/12.0/odoo/service/server.py#L444)
Thus, this condition is never fulfilled.
On top of that, this was masked by the first part of the condition,
checking that the 'test/common.py' has no "post_install" string.
The "test" directory does not exists in Odoo ( but "tests" exists) , so
the condition was always falsy.
Finally, a build can be marked as "ok" when he is killed and no errors
are found until the kill.
With this commit:
* The legacy grep for post_install is removed as …
=> [FIX] runbot: make the cpu limit the same as the runbot timeout

runbot/models/build.py
When running Odoo in the Docker container, the username used to connect
to the database is the username defined in the docker container
(actually odoo).
A problem may arise if the user of the runbot process is not the same.
An authentication error is then raised by postgres because of the
username mismatch.
With this commit, the '-r' parameter of Odoo is added to the command
with the runbot process username.
=> [FIX] runbot: add dbuser parameter to the odoo cmd

runbot/controllers/frontend.py, runbot/models/branch.py, runbot/templates/frontend.xml
When the quickconnect button is used, the last running build is
searched in the last 10 builds. If no running build is found, the last
one is rebuilt, even if it's a nightly build.
With this commit, the quickconnect build is choosen only among the ones
with the same config.
=> [FIX] runbot: choose quickconnect build with same config

runbot/models/build.py, runbot/models/build_config.py, runbot/templates/build.xml, runbot/tests/__init__.py, runbot/tests/test_build_config_step.py, runbot/views/build_views.xml, runbot/views/config_views.xml
In a create config, a parent result is computed based on children
results
In some situations, it could be handy to ignore the result of some
sub-builds.
Example: the nightly tests are just the children of on nightly build
with a create config. The external tests are failing randomly and as a
consequence, the nightly result is always red. On the other hand,
keeping the test running, just to have logs is a good idea.
With this commit, a config_step of type create can be marked as
orphan_result, that way, the result is not taken into account in for the
parent build result.
=> [IMP] runbot: allow a parent to ignore some child builds

runbot/data/Dockerfile
In order to use the new test odoo/odoo#33724 the es-check tool is needed
in the Docker runbot image.
To merge once the above PR is validated and merged
=> [IMP] runbot: add es-check tool to the Docker image

runbot/models/repo.py
When a runbot instance is scheduling builds, the numbers of builds
depends of a global ir.config_parameter. Even if one of the runbot
instance is running on a more powerful systsem, its number of workers is
limited by this global parameter.
With this commit, this parameter still exists but can be overriden by
specific ir.config_parameter.
For example, if the host 'runbot24.odoo.com' has more cpu power, the
number of workers for this host can be specified in the
ir.config_parameter named 'runbot24.odoo.com.workers'.
=> [IMP] runbot: allow to configure workers per host

runbot/models/repo.py
When getting new refs, a lot of them are really old and the
find_new_commits is called for each one and thus browsing branches.
With this commit, refs older than configured max_age are ignored.
Co-authored-by: Xavier Dollé (xdo@odoo.com)
=> [IMP] runbot: only consider refs newer than max_age

runbot/models/build_config.py
When creating multi builds config steps, the force_build option is often
forgotten. In that case, the multi builds are detected as duplicate of
the first one.
With this commit, when asking for more that one multi build, the
force_build is chnaged to to True.
=> [FIX] runbot: set force_rebuild when creating multi builds

runbot/models/build.py
In some conditions, Docker can take a little time to start a container.
In that case, if the runbot checks that the container is running before
it starts, runbot consider the job as finished. It the tries to grep the
logs and, as expected, it does not find the "Modules loaded".
With this commit, we consider young builds (less than 15 sec) as
running, giving more time to Docker for starting it.
=> [FIX] runbot: avoid "Modules loaded not found in logs"

.gitignore, runbot/common.py, runbot/container.py, runbot/models/build.py, runbot/models/build_config.py, runbot/models/build_dependency.py, runbot/models/repo.py, runbot/templates/build.xml, runbot/tests/test_build.py, runbot/tests/test_schedule.py, runbot/views/build_views.xml, runbot/views/repo_views.xml
Multibuild can create generate a lots of checkout, especially for small
and fast jobs, which can overload runbot discs since we are trying not
to clean build immediatly. (To ease bug fix and allow wake up)
This commit proposes to store source on a single place, so that
docker can add them as ro volume in the build directory.
The checkout is also moved to the installs jobs, so that
builds containing only create builds steps won't checkout
the sources.
This change implies to use --addons-path correctly, since odoo
and enterprise addons wont be merged in the same repo anymore.
This will allow to test addons a dev will do, with a closer
command line.
This implies to change the code structure a litle, some changes
where made to remove no-so-usefull fields on build, and some
hard-coded logic …
=> [IMP] runbot: share sources between builds

runbot/models/build.py, runbot/models/build_config.py
When an Odoo instance is run in a Docker container, it listen on all
interfaces by default and a bridge interface is used to communicate with
the outside world.
This bridge interface is necessary to allow the instance to send logging
messages into the runbot postgresql database.
Even though Docker isolate the container from the oustide world, it's
still possible to reach the Odoo instace from the runbot host and worse,
from other Docker containers using the same bridge interface.
To confirm the  Murphy's law, it finally happened with this commit
odoo/enterprise@0ba0ef99de that scanned the ip range of the interface,
disturbing other builds.
One solution would be to create a bridge interface for each instance to
isolate each Docker but that would imply a big change to garbage collect …
=> [FIX] runbot: prevent inter Docker communication

runbot_merge/github.py, runbot_merge/models/pull_requests.py, runbot_merge/tests/test_basic.py
* when rebasing, store a map of rebased to source, that way it'll be possible to link cherry-picked forward ports to the originally integrated commit rather than just the one from the PR (which was likely not itself integrated as the straight merge mode is somewhat rare: as of 5600 PRs merged so far only 100 were straight merged)
* while at it, store the "merge head" of the PR (whether squashed, merged or rebased) and put *that* in the commit message: the information is already provided through github back-referencing the commit through the "closes" tag automatically added but given point 1 it shouldn't take much to provide accurate commit info explicitly
=> Map PR commits to integrated commits in mergebot

runbot_merge/controllers/__init__.py, runbot_merge/models/pull_requests.py, runbot_merge/tests/remote.py, runbot_merge/tests/test_basic.py
Unlike stagings, splits would not get cancelled / updated if a PR was moved out of "ready" state (updated, cancelled, unapproved, …). The split would then get staged straight without checking the PR's state, potentially staging closed or unreviewed PR, or updated PRs which hadn't been re-CI'd yet.
=> PR splits should be updated on PR state change

runbot_merge/github.py, runbot_merge/models/pull_requests.py
In case of error while fast-forwarding a staging to its source, we'd
log the target to which we couldn't FF. Sadly this relied on a
`repo_name` variable which (likely since the introduction of the
"safety dance" fast forwarding) can not actually be set in case of
failure.
=> Fix fast-forward error logging message

runbot/models/build_error.py, runbot/views/build_error_views.xml
The Many2many related on a Many2many does not map the ids as expected.
With this commit, the records are mapped in a compute.
It also fixes an uppercase letter was used in the children_build_ids field name.
=> [FIX] runbot: properly compute children_build_ids

runbot/models/repo.py
When finding new commits, if there is more pending builds on a repo than
the running_max parameter, the exceeding builds are skipped.
As a result, when nightly builds are created on the runbot, it happens
that some of them are skipped.
Also, since e51412d , only refs newer than max_age are builded; thus the
logic is not needed to prevent rebuild of olds refs in case of a fresh
runbot install.
=> [FIX] runbot: remove skip old builds logic

runbot/models/repo.py
Even if present and editable the user, changing the sequence
of a repository has no effect
Fix by adding missing _order on runbot.repo model
=> [FIX] runbot: correctly order repo by sequence

runbot/static/src/js/runbot.js, runbot/templates/branch.xml, runbot/templates/build.xml
When using the runbot frontend, it's sometimes very frustrating when
trying to copy branch name, some mouse gym is necessary.
With this commit, a copy to clipboard button is added near the branch
name on the frontend.
=> [IMP] runbot: add a copy to clipboard button for branch

runbot/data/runbot_build_config_data.xml, runbot/models/build.py, runbot/models/build_error.py, runbot/models/event.py, runbot/models/repo.py, runbot/views/build_error_views.xml, runbot/views/build_views.xml, runbot/views/error_log_views.xml
- Add a keep running flag on the build to allow a build to stay in
running state until the flag is switched off ( or the build killed)
- Do not update configs and config_steps data
- Add a first/last_seen_build and first/last_seen_date on build.error
- Children error builds now include the parent builds too
- Use a notebook on build.error form view to display builds and linked
errors
- Update result when a build triggers a change from 'warn' to 'ko' too
=> [IMP] runbot: various improvements

runbot/models/build.py
When a build only create sub-builds, the build_time is verry small (a few seconds),
and this information is not relevant. This commit propagates end_time to parent_build
if parent_build is done or running.
=> [IMP] runbot: propagate end_time to parent_build

runbot/models/build.py, runbot/models/build_config.py, runbot/models/event.py, runbot/tests/__init__.py, runbot/tests/test_event.py
When a build is running, a cron, an evil query or something else can
start to fill and bloat the runbot ir_logging table.
With this commit, a log_counter field is added on the build, starting at
100. The SQL trigger decrement this counter after a line is inserted.
When the counter drops to 0, a the last log line contains a message
stating that the limit has been reached. Further log lines are dropped
for this build step.
The counter is reset to 100 before each step.
The runbot itself is still able to add logs lines through the build _log
method.
Thanks @Xavier-Do for the smart idea.
=> [IMP] runbot: number of log lines per build

runbot/models/repo.py
Using `repo.hook_time = None` and `repo.mode = hook` the cron run fetch command in an infinite-loop.
Using by default the current date the issue is fixed because the first command is a "git clone" if the path is not exists then the last time is now for first time.
=> [FIX] runbot: Avoid infinite loop fetching

runbot/__manifest__.py, runbot/migrations/4.5/post-migration.py, runbot/models/build.py, runbot/models/build_config.py, runbot/tests/test_build.py
Actually some Odoo modules are black_listed from a set hardcoded in the
runbot code. On some cases, one needs to blacklist custom modules,
preferably in a config_step.
With this commit, a mod_black_list field is added on the Repo and on the
ConfigStep. They optionaly hold a comma separated list of fnmatch patterns. If a
module name match any of the pattern, it's filtered out from the build.
=> [IMP] runbot: uses fnmatch to black list modules

runbot/common.py, runbot/container.py, runbot/models/build.py, runbot/models/repo.py
In different situations, a docker container may stay alive even if the
build global_state is done. This can lead to a build failure when a
build wants to go in running state and tries to expose the same ports as
the left over build.
=> [FIX] runbot: clean running dockers with done builds

runbot/data/Dockerfile, runbot/models/build_config.py
With this commit, a new boolean field "flamegraph" is added on the
build_config to allow a flamegraph generation.
In order to be able to generate a flamegraph during a runbot build, the
flamegraph package is added to the Docker image as well as the
flamegraph.pl tool.
=> [IMP] runbot: allow to generate a flamegraph during a build

runbot/__init__.py, runbot/__manifest__.py, runbot/models/build_config.py, runbot/views/config_views.xml, runbot/wizards/__init__.py, runbot/wizards/multi_build_wizard.py, runbot/wizards/mutli_build_wizard_views.xml
Creating multi builds configs can be tedious. One must create 2 build
configs and 2 build config steps in the right order.
With this commit, a simple wizard is added that creates those 4
configurations by simply filling 4 fields.
=> [IMP] runbot: add a multibuild wizard

runbot/controllers/frontend.py, runbot/models/build_config.py, runbot/models/build_error.py, runbot/tests/test_build_config_step.py
A typical use case when an error is detected is to disable
this test by adding a negated test-tags on config
step 'all' and 'split_all'. This commit will help
to do that by adding a test_tags management on build error.
The user define a test_tag that will only execute failling test.
if a config step has the flag enable_auto_tags, the test tag will
be negated and added to config test-tags.
=> [IMP] runbot: add auto-test-tags-management.

runbot/container.py, runbot/models/build_config.py, runbot/views/config_views.xml
Since 81fefee, the container.py CLI does not work as expected.
With this commit, the CLI is working, a new arg was added to test
flamegraphs and the dump is adapted to mimic the runbot.
Also, a small issue is fixed in the zip file creation. Before the zip
creation, the directory is changed, if the directory change fails, the
zip is created from the current directory which is removed by zip at the
end of the process. That could lead to the deletion of the build dir.
=> [FIX] runbot: fix container cli tests

runbot/container.py, runbot/models/build.py, runbot/models/build_config.py, runbot/tests/__init__.py, runbot/tests/test_build.py, runbot/tests/test_command.py
When starting an odoo instance with Docker, a very long command line is
computed and appears in the logs.
With this commit, an .odoorc configuration file is written ind the build
dir and mounted in the Docker container.
Previously, the runbot .odoorc/.openerprc file was mounted to share some
parameters. Now, if that file exsists, its content is merged with build .odoorc.
=> [IMP] runbot: use a config file to simplify args

runbot/models/build.py, runbot/models/build_config.py, runbot/models/repo.py, runbot/tests/test_repo.py
_find_new_commits will check if a build exists with current branch HEAD
before creating build. This is crutial to avoid to create a new build
at each loop turn. The problem is that in some rare cases, when
forcepushing an old head on a branch, the build won't appear and the only
way to update the branch is to find the corresponding build that may be
hidden in hitory. This my be consfusing to the user that will rebuild the
created build with a commit that doesn't represent the head of the branch.
This commit only search for the last build of each branch, in order to
only skip build creation if the last build as the same hash. The new
created build should be marked as the duplicate of the first one.
=> [IMP] runbot: create build when old HEAD is force-pushed

requirements.txt, runbot/common.py, runbot/container.py, runbot/models/build.py, runbot/models/build_config.py, runbot/models/repo.py, runbot/tests/__init__.py, runbot/tests/common.py, runbot/tests/test_branch.py, runbot/tests/test_build.py, runbot/tests/test_build_config_step.py, runbot/tests/test_build_error.py, runbot/tests/test_cron.py, runbot/tests/test_event.py, runbot/tests/test_frontend.py, runbot/tests/test_repo.py, runbot/tests/test_schedule.py
A lot of things have to be mocked during runbot tests, as a consequence,
a lot of patch decorators accumulate in a big stack uppon some tests
methods.
Also, a lot of mocks are used multiple times among tests.
With this commit, a new RunbotClass is added that comes with patches
ready to be started. A start_patcher helper method is available to start
a patch and add the appropriate stop in a cleanup.
Also, when a build is created in the tests, the _get_params method is
always called, resulting in an annoying git warning.
With this commit, a create_build method is added on the test class, that
way the _get_params is always mocked when a build is created.
=> [IMP] runbot: refactor tests

runbot/container.py, runbot/models/build.py, runbot/tests/test_build.py, runbot/tests/test_command.py
When creating an .odoorc file to store configuration that are proper for
the runbot, the 'data-dir' key was used instead of data_dir.
Because of that, the data dir was created in the default dir and thus,
not included in the zip file of the dump, causing some runbot
steps to fail.
=> [FIX] runbot: fix typo in data_dir/data-dir

runbot/controllers/frontend.py, runbot/models/build.py, runbot/static/src/less/runbot.less, runbot/templates/build.xml
Now that we can split build in multiple children builds, it can be confusing to read/find logs.
This PR is an attempt to show the logs of the sub-builds on the parent build log page.
=> [IMP] runbot: show sub-builds logs on parent build

runbot/models/branch.py, runbot/tests/test_branch.py, runbot/views/branch_views.xml
Migration tests comming on runbot, it will be usefull to have quick
way to obtain branches related to current build.
This commit adds a field for the colsest sticky branch, previous version
and intermediates stickies.
Example when last sticky is saas-13.2:
branch_name: master-test-tri
closest_sticky: master
previous_version: 13.0
intermediate_stickies: saas-13.1, saas-13.2
=> [IMP] runbot: add relation between branches

runbot/models/build_error.py, runbot/tests/test_build_error.py
When trying to remove test_tags on a build_error, the validation fails
because it tries to iterate on False. Also, the ValidationError
exception was not properly imported.
With this commit, the validation is fixed and a test is added.
=> [FIX] runbot: fix build_error test tags validation

runbot_builder/builder.py
When the linux logrotate system rename the runbot logfile used by the
new builder script, the script continues to write in the rotated file.
With this commit, the WatchedFileHandler is used. This handler is
specially crafted to handle this situation, it detects the file renaming
and automatically changes to the new file that have the old filename.
=> [FIX] runbot: use a logging handler that loves logrotate

runbot/container.py, runbot/data/Dockerfile
As the Odoo requirements were recently updated, the last RUN entry in
the Docker image was rebuilt on our runbot instances.
Since that moment the coverage builds are failing with an import error.
After investigation, it appears that the latest coverage version modifies the sys.path.
A bug report was written for coverage: https://github.com/nedbat/coveragepy/issues/919
For that reason, this commit freeze the coverage version until this bug
is fixed.
Also, the os import problem in conatainer.py is fixed.
=> [FIX] runbot: temporarily freeze the coverage version

runbot/models/branch.py
When changing the sticky value in a branch form, it triggers the
computes of previous version and intermediate versions.
In the onchange situation, the branch.id is a NEW id and it fails with a
traceback.
With this commit, a verification is made to ensure that the id is there.
=> [FIX] runbot: fix compute previous_version and intermediates

runbot/fields.py, runbot/models/build.py, runbot/tests/test_build.py
When two steps in the same build needs to exchange informations, some
hacks have to be used. E.g. using the extra_params fields to store comma
separated values.
With this commit, a data field is added alongside with two helper
methods that store/retrieve the content of the field as a json string.
=> [IMP] runbot: add a data field on build

runbot/controllers/frontend.py, runbot/static/src/js/runbot.js, runbot/templates/build.xml
Killing, waking or rebuilding currently redirects to the repository root which is generally useless.
Since it's very easy to go from a build to its repository, redirect to the "most useful" build instead:
* the current build for kill & wakeup
* the new build on rebuild
Provided two versions of the implementation:
* one keeps the current controllers & deduplicates and fixes the final URL building
* the other one merges all 3 controllers into a single one
=> Fix useless redirections on build actions

.gitignore, runbot/models/build.py, runbot/models/host.py, runbot/models/repo.py, runbot/tests/test_cron.py, runbot_builder/builder.py
At this moment, the Docker image is built at the beginning of each
runbot build. This blocks the _scheduler while the image is built.
With this commit, the image is built before calling the _scheduler and
is not linked to a runbot build.
Also, the necessary dirs are created in the static path.
=> [IMP] runbot: build docker image once per loop turn

conftest.py, forwardport/models/project.py, forwardport/tests/conftest.py, forwardport/tests/test_weird.py, forwardport/tests/utils.py, runbot_merge/__manifest__.py, runbot_merge/migrations/11.0.1.1/pre-migration.py, runbot_merge/models/pull_requests.py, runbot_merge/tests/conftest.py, runbot_merge/tests/test_basic.py, runbot_merge/tests/test_multirepo.py, runbot_merge/views/mergebot.xml
* move the required statuses (CI jobs) from the project to the repository so it's possible to co-develop repos with different CI sets / requirements and keep them coherent (e.g. doc in a different repo or something)
* make it possible to whitelist/blacklist branches on repositories, branches remain linked to a project but can further be restricted to not apply to some repos
=> Repository-level customisations

conftest.py, forwardport/models/forwardport.py, forwardport/models/project.py, forwardport/tests/test_weird.py, runbot_merge/controllers/__init__.py, runbot_merge/github.py, runbot_merge/models/pull_requests.py
And various tangentially-related-at-best improvements.
The meat of it is (hopefully) the fixing of #262 by hooking into updates to the project and scheduling the generation of new intermediate forward port PRs IF a branch is created within the existing sequence (rather than at either end) and there are "live" (not merged) forward-ports which span over the new branch.
ping @d-fence I guess?
=> Add support for freezes to forwardbot

runbot/models/build.py, runbot/models/host.py, runbot/models/res_config_settings.py, runbot/views/res_config_settings_views.xml
Since cb05f2b9d8, when creating a database, the template1 is used, this
allows to customize the template and install some needed Postgress
extensions.
Unfortunately, it's also a source of build failures. For example, if the
pg_activity util is used on a runbot host, database creation may fail
with a message like this:
source database "template1" is being accessed by other users
It's because pg_activity needs a database and uses template1.
With this commit, template1 is still used by default but can be changed
with a system parameter. That way, a custom template can be created on
runbot hosts and used when creating DB in builds.
=> [FIX] runbot: use a custom template to create db

forwardport/models/project.py, forwardport/tests/test_limit.py, forwardport/tests/test_simple.py
On github wiki, the link changed from https://github.com/odoo/odoo/wiki/Mergebot to https://github.com/odoo/odoo/wiki/Mergebot-and-Forwardbot
Reflect these changes in the comments posted by the bot.
=> [FIX] forwardport: update the wiki link (13.0)

runbot/data/Dockerfile
With this commit, it will be possible to play with different chrome
versions without impacting all runbot instances.
Chrome issues summary:
* 71: innerText linefeed issue
* 74: random chrome crash
* 80: V8 pointer compression exceed Odoo memory limits
=> [IMP] runbot: set google-chrome version precisely

runbot/__manifest__.py, runbot/common.py, runbot/models/build.py, runbot/models/repo.py, runbot/tests/common.py, runbot/tests/test_build.py, runbot/views/build_error_views.xml, runbot/views/build_views.xml
When a build age reaches the gc_days parameter, its database is dropped
and its directory is removed.
With this commit, two fields are added in order to keep some builds
longer that the defined gc_days.
The gc_delay field on the build allows to add a delay (in number of
days) that is added to its gc_days to compute the gc_date.
The gc_date field is the date when the cleaning will occur.
Also, a test is added and the RunbotCase test class is improved to allow
the stop of a patcher.
=> [IMP] runbot: improve local cleanup

runbot/models/repo.py, runbot/templates/build.xml
When a new commit is found, a rebuild is forced on sticky branches
builds in repositories that depends on the new commit repository.
If one of the repo is protected by groups, the main page gives access
errors for public users and finally leads to a CPU overload.
With this commit, the feature is removed as it will be re-implemented in
custom config steps.
=> [REM] runbot: remove reverse dependency build feature

runbot/models/build_config.py, runbot/tests/common.py, runbot/tests/test_build_config_step.py
When creating a subbuild from a custom python job/cron, some data can
be given through config_data or extra_params to change another step behaviour.
An example is to give a specific -i to an install job in order to
install different modules from the parent build. Anyway since we
are using the same install step in this case, all databases will
have the same name, and the name may not be correct in regard to
the database content.
This commit allows to give a config_param on build giving the default
db_name to use in an install step.
=> [IMP] runbot: custom db_names for install and run jobs.

runbot/models/build_config.py, runbot/tests/test_build_config_step.py
When a build.config is copied, the config steps are not copied.
The steps have to be explicitly ordered otherwise it leads to a
traceback when trying to copy a 'run' step which  have to be the last
one.
=> [IMP] runbot: copy steps when duplicating a config

runbot/common.py, runbot/models/build.py, runbot/models/build_config.py, runbot/models/event.py, runbot/static/src/css/runbot.css, runbot/templates/build.xml, runbot/tests/test_build.py, runbot/tests/test_event.py
With this commit, a kind of markdown is allowed in log messages.
Following patterns are supported:
**strong**
~~striketrough~~
__underline__
[link](target)
@icon-font-awesome-class
=> [IMP] runbot: allow pseudo markdown in log messages

runbot/container.py
Currently runbot runs with unaccent installed (always) but apparently not *enabled* via the CLI flag.
According to @tbe-odoo and @amigrave both the saas and pass run with `--unaccent` explicitly set in the CLI. It would therefore be logical to do the same for runbot. Might be that we
*Alternatively* we could just deprecate and ignore the `--unaccent` flag: the features of base which use  it [go through the has_unaccent registry flag](https://github.com/odoo/odoo/blob/c8e79869a37b87101d64e4703401f409358a2099/odoo/modules/registry.py#L144-L148) (or [`get_unaccent_wrapper` which uses it](https://github.com/odoo/odoo/blob/9ce78bff5fb084de67034bf54a814d1f30ffda46/odoo/osv/expression.py#L460-L463)), which both checks the cli/config flag *and* checks if the extension is installed in the …
=> Enable unaccent switching to run mode

runbot/models/build_config.py
Before intensive python steps, every build exept create build should have logs.
This is not true since now many python steps are creating build, leading
to 404 links to inexisting logs file.
Checking That a step is a docker build looks like a good heuristic since since
most of the time the log file will be the one created by docker. In all case we
can access other logs files in browsing /logs.
A future improvement would be to listdir logs to create all links.
=> [FIX] runbot: better log list

runbot/models/host.py, runbot/models/repo.py
From time to time, a git repo gets corrupted. When it happens, the fetch fails but the runbot still tries to run builds.
This PR is an attempt to catch those failures and auto-disable the runbot host on which the repo is corrupted.
TODO:
* verify that there are still enough runbot host before disabling the failing host
* verify where to catch the Exception
=> Handle fetch failure

runbot/container.py, runbot/models/build_config.py, runbot/tests/test_build_config_step.py
When coverage is computed, a post command is used to generate the HTML
report. In order to use the coverage result locally the HTML report is
not enough.
With this commit, an XML report is also generated. It's a single xml
file, downloadable from the build result web page.
The _post_install_command method is renamed into its plural form because
it was useless to return only one command.
=> [IMP] runbot: add coverage xml export

runbot/templates/build.xml
By default, the error was displayed with arrow pointing UP, not down
=> [FIX] runbot: displayed collapsed error

runbot/templates/build.xml
When a build is a duplicate, the connections links are not visible
because the local_state is "duplicate".
=> [FIX] runbot: show connect links when build is a duplicate

runbot/__manifest__.py, runbot/models/__init__.py, runbot/models/branch.py, runbot/models/build.py, runbot/models/build_config.py, runbot/models/build_stat.py, runbot/models/build_stat_regex.py, runbot/security/ir.model.access.csv, runbot/tests/__init__.py, runbot/tests/test_build_stat.py, runbot/views/build_views.xml, runbot/views/config_views.xml, runbot/views/stat_views.xml, runbot/wizards/__init__.py, runbot/wizards/stat_regex_wizard.py, runbot/wizards/stat_regex_wizard_views.xml
When a build is done, various numerical informations could be extracted
from log files.  e.g.: global query count or tests query count ...
The extraction regular expression could be hard-coded in a custom step
but there is no place holder where to store the retrieved information.
In order to compare results, we need to store it.
With this commit, a new model `runbot.build.stat` is used to store
key/values pair linked to a build/config_step.  That way, extracted
values can be stored.
Also, another `runbot.build.stat.regex` is used to store regular
expressions that can be used to grep log files and extract values.
The regular expression must contain a named group like this:
`(?P<value>.+)`
The text catched by this group MUST be castable into a float.
Optionally, another named group can be …
=> [IMP] runbot: add a build stat model

runbot/models/build_config.py, runbot/templates/nginx.xml
When deployed behind nginx reverse proxy and https, the Odoo proxy-mode
must be enabled.
=> [FIX] runbot: use proxy-mode for running instances

runbot/models/branch.py
Since we store the target_branch_name, filtering out pull head names
that contains `patch-` is not necessary anymore.
This commit is one first step towards a clean refactoring.
=> [IMP] runbot: remove pull_head_name patch filter

forwardport/models/project.py, forwardport/tests/test_weird.py, runbot_merge/models/pull_requests.py
Provides a `skipci` command to PR reviewers. This makes it so the
followup PRs (after the first one) get created immediately, without
waiting for CI to succeed on a given forward-port PR.
This can be useful if for some reason a change *must* be merged in
branch N+1 before it can be merged in branch N.
Fixes #363
=> [ADD] forwardport: ability to skip CI when forward porting

forwardport/__manifest__.py, forwardport/migrations/13.0.1.1/post-reminder-date.py, forwardport/migrations/13.0.1.1/pre-tagging.py, forwardport/models/forwardport.py, forwardport/models/project.py, forwardport/tests/test_simple.py
The exponential backoff offsets from the write_date of the children
PRs, however it doesn't reset, so the offsetting gets bumped up way
more than originally expected or designed if the child PRs are under
active development for some reason.
Fix this by adding a field to specifically record the date of merge of
a PR, and check that feature against the backoff offset. This should
provide more regular and reliable backoff.
Fixes #369
=> [IMP] forwardport: reliability of PR reminders

runbot/data/Dockerfile
The postgresql-client in the Dockerfile is the one provided by the
Debian package. When the postgresql server on the host has a higher
version than the client, some builds may fail (for example, dumping a
database with the pg_dump).
With this commit, the postgresql-client 12 from the postgresql repo is
used in the Dockerfile.
=> [IMP] runbot: install postgresql-client 12 in Dockerfile

runbot/container.py, runbot/tests/test_command.py
Docker container names are derived from the dest and step name. The dest
is itself derived from the branch name.
In some rare cases, it happens that a character not allowed by Docker
appears in the container name computed by the runbot.
With this commit, a sanitize_container_name function is used to remove
unallowed characters at the container utility level.
=> [FIX] runbot: avoid unallowed characters in docker names

runbot/data/Dockerfile
The ocrmypdf suite of tools are needed by task #2238654.
Altough this package will be optional for Odoo users, it has to be
usable by dev's in order to test and/or fix the feature.
=> [IMP] runbot: add ocrmypdf package to Dockerfile

runbot/tests/test_repo.py
73f720a55c8d2c3b3f867e293ff5cb6fb93281a7 refactored the runbot tests, and amongst other things created a single patch point for the "mock root" as a testcase attribute.
One of the tests was missed during that refactoring, likely because it's skipped by default.
=> [FIX] runbot: mis-migrated test

conftest.py, forwardport/data/views.xml, forwardport/models/project.py, runbot_merge/__manifest__.py, runbot_merge/controllers/__init__.py, runbot_merge/migrations/13.0.1.4/pre-migration.py, runbot_merge/models/pull_requests.py, runbot_merge/models/res_partner.py, runbot_merge/security/ir.model.access.csv, runbot_merge/tests/test_basic.py, runbot_merge/tests/test_by_branch.py, runbot_merge/tests/test_oddities.py, runbot_merge/views/mergebot.xml, runbot_merge/views/res_partner.xml
* split statuses into their own object which can be filtered on a per-branch basis
* further allow statuses to be filtered on being required for PRs or stagings (or both, or none though that's not very useful)
* add support for overriding statuses
=> Make statuses more flexible

runbot_merge/models/pull_requests.py
When using @fw-bot close, a feedback would be created without a
message (rather than e.g. with an empty one). As a result, the
feedback-sending cron would crash, but not before having closed the
corresponding PR.
This would lead to closing the PR in a loop & spamming the logs with
tracebacks.
=> [FIX] runbot_merge: stuck feedback cron

runbot/data/Dockerfile
The pdf417 python library is needed for the l10n_cl_edi. As this module
is not mandatory, the library was not added in the requirements.txt
file.
In order to test the feature on the runbot, this commit adds the library
in the Docker container.
Related work:
odoo/odoo#54995
odoo/enterprise#12080
odoo/enterprise@8290bfaf
=> [IMP] runbot: add pdf417 library

runbot/models/runbot.py
The old order based on status is not really needed anymore:
- Scheduled builds have a special condition and already have a low priority.
- Indirect builds don't exist anymore
- It is actually questionnable to postpone rebuild. Sometimes they are needed but stuck.
This new proposition will keep subbuild scheduling close to parent build. Some build may take 2 hours
because they are parallelized and children are stuck. Priority should be defined by top parent.
=> [IMP] runbot: improve build order

runbot/models/build_config.py, runbot/views/config_views.xml
Currently there is no way that I can see to configure extra parameters or environment variables to run_odoo build config steps. It is possible on install steps, but not on run steps. This PR adds that capability.
This is useful in cases where a module needs to be run as a server wide module. For example [OCA/queue](https://github.com/OCA/queue/tree/13.0/queue_job).
=> [IMP] runbot: add extra parameters and environment variables to build config step

runbot/container.py, runbot/models/build.py, runbot/models/build_config.py, runbot/tests/test_build_config_step.py
When calling a step from a python step, it is impossible to alter some parameter, the only solution is to copy all step code.
With this change, python step are now able to override docker_run parameter of another step by modifying the dict returned by run_* steps
and assigning the result to "docker_params".
This will mainly be used to set the correct docker_image for migration pre and post test. This can also be used to alter a command,
like removing the pip install or adding extra pre/post operation on the command.
=> [IMP] runbot: call docker_run outside steps

runbot/models/build_config.py, runbot/models/bundle.py, runbot/views/bundle_views.xml
For now, the sticky flag is used to define bundle to use as target to upgrade.
The plan for future is to continue to test upgrade, even if the bundle is not sticky anymore.
This new flag will allow to remove sticky for old branche.
This will also allow to disable upgrda tests for still sticky branches when needed.
This commit also filter source bundle based on this flag
(before that all base bundle where used as source, even if not sticky)
=> [IMP] runbot: add to_upgrade option

runbot/controllers/badge.py
Trying to use a badge on a repo which is restricted to one or more groups in runbot will result in a 403 error every time the badge URL is called. This PR fixes that problem by using elevated permissions to bypass security rules.
The assumption is that we want the badge to load regardless of the security settings and that build status is not a confidential piece of information.
=> [IMP] runbot: serve badges for projects which are not accessible to the public

runbot/models/build_config.py
Since 3657a65b20 docker_run is called outside of the step and python
steps have to set the `docker_params` variable. This breaks the computed
`log_list` because the string `docker_run(` is searched in python
steps code to determine if it's a docker_step.
With this commit, the `docker_params = ` is searched instead.
=> [FIX] runbot: fix _is_docker_step to incidentallly fix log menu

runbot_merge/views/templates.xml
It was not evaluated and rendered to something like
https://mergebot.odoo.com/odoo/odoo/pull/linked.url
Courtesy of Xavier Dollé (xdo)
=> [FIX] runbot_merge: correct Linked PRs URLs

runbot/models/build_config.py
When a build is reaching the run_run_odoo step, a database has to be
set. If none are found in the build params, the one from the last step
is choosen. Historically, the last one in the `Split` config was `all`
but now, the last one is `base`.
With this commit, if none are found in build params, `all` is choosen if
found in any install config steps. As a default, the one from the first
step is choosen.
=> [FIX] runbot: improve the way a database name is choosen for running

runbot/tests/test_runbot.py
Since odoo/odoo@824a651 the test_warning_from_runbot_abstract was
failing for a good reason, the `browse` parameter was a recordset
instead of an id.
=> [FIX] runbot: browse a valid record id in test_warning

runbot/controllers/frontend.py, runbot/tests/test_commit.py
When a status cannot be sent to github, the status is created in
database but the `sent_date` field is not set.
Because of that, the status cannot be sent manually from the frontend.
With this commit, that kind of status can by tried again.
=> [FIX] runbot: allow to retry to send a status

runbot/templates/utils.xml
Using database name as subdomain will set the web.base.url correctly when connection for the first time using this link
This will unfortunatelly break connect all and connect base links if dns and nginx are not setup.
This won't fix the web.base.url when connecting with the Connect (database selector) button either.
=> [FIX] runbot: use database name subdomain

runbot/models/bundle.py
If you try to manually create bundle, Odoo will crash, because it will
try to use `name` value that is not set yet. For that we start computing
host_id once `name` is entered.
Particularly, you would get this error:
```python
Traceback (most recent call last):
File "/home/oerp/odoo13/odoo/odoo/http.py", line 624, in _handle_exception
return super(JsonRequest, self)._handle_exception(exception)
File "/home/oerp/odoo13/odoo/odoo/http.py", line 310, in _handle_exception
raise pycompat.reraise(type(exception), exception, sys.exc_info()[2])
File "/home/oerp/odoo13/odoo/odoo/tools/pycompat.py", line 14, in reraise
raise value
File "/home/oerp/odoo13/odoo/odoo/http.py", line 669, in dispatch
result = self._call_function(**self.params)
File "/home/oerp/odoo13/odoo/odoo/http.py", line 350, in …
```
=> [FIX] runbot: _compute_host_id

runbot/templates/dockerfile.xml
When choosing to install Chrome in a Dockerfile, the chrome version is
downloaded from Odoo nightly server. This make it difficult to test
with different versions of Chrome.
With this commit, we allow to install from Google in Docker files.
By default, the install remains from Odoo Nightly server but if the key
`custom_values['chrome_source']` is set to 'google' in a Dockerfile,
the specified version will be downloaded from Google servers when the
Docker image is built.
This PR also contains a feature to disable the installation of `requirements.txt` file in Dockerfile.
=> [IMP] runbot: allow to install Chrome from google

runbot/models/build_config.py, runbot/views/config_views.xml
As a developer of modules on top of Odoo, I would like to exclude Odoo's files from the coverage report as I am more interested in the coverage of my own modules. By having Odoo's files listed alongside my own, the total coverage score is diluted.
This commit adds a field to the build config step to enter a comma separated list of paths to omit from coverage.
I'm not sure if it will be of any utility to Odoo SA, but will be useful for all the module developers out there and does not get in the way if not used.
=> [IMP] runbot: add an option to exclude paths from coverage report

runbot/__manifest__.py, runbot/controllers/frontend.py, runbot/models/repo.py, runbot/static/src/js/stats.js, runbot/templates/assets.xml, runbot/templates/build.xml, runbot/templates/build_stats.xml, runbot/templates/bundle.xml, runbot/templates/utils.xml, runbot/views/repo_views.xml
Since 360e31ade4, it's possible to add statistics values to build
results but there was no practical way to analyze them.
With this commit, there is a new button on the bundle page that leads to
a chart page that displays those values.
The default reference build is last known good build of the bundle.
Values are filtered by key and only the most significant values are
displayed. The user can then refine the chart by changing the reference
build or the key and a few other options.
Co-author: Xavier-Do <xdo@odoo.com>
=> [IMP] runbot: add a chart page for build stats

runbot/controllers/frontend.py, runbot/static/src/css/runbot.scss, runbot/static/src/js/stats.js, runbot/templates/build_stats.xml
- Adds a complete legend enabelling to display a custom subset of modules.
This is mainly to enable a vertical scroll on list since chart-js default
legend will be displayed on multiple column.
- Adds a "Noisy" order mode to find non-deterministic modules.
- Changes the build selection mode to a center one to easylly center
build of interrest and add a forward button.
- Small ui tweaks/fix to match new selection logic.
=> [IMP] runbot: Improve stats display

runbot/common.py, runbot/tests/test_event.py
When code blocks were containing markdown like text, the inside of the coden block was also formated.
This commit removes the code blocks before applying other formating and place them back at the end.
closes #481
=> [FIX] runbot: fix markdown code

runbot/templates/frontend.xml
When a build slot is hidden in the batch tile but is responsible of the
batch failure, the failure reason may not be obvious for the user.
With this commit, an hidden slot appears if the slot build is in
failure.
=> [IMP] runbot: show red slots in batch tile

runbot/views/dockerfile_views.xml
When a dockerfile to_build field is False for any reason and a new
runbot is setup, it's easy to miss the point and builds that involves
this particular Dockerfile will fail on the new runbot.
With this commit, the Dockerfiles tree view is improved to easily spot
those kind of problems:
- to_build field is visible and the Falsy lines are in yellow (warning)
- the empty Dockerfile's are in red (danger)
- versions are now visible in the tree view too
=> [IMP] runbot: enhance dockerfile tree view

runbot/models/build.py
The test in the original code will never fire because the value searched for is not in the keys of the dictionary, but in one of the lists which are in the values. Work around this by maintaining a reverse dictionary module name -> commit and use this for the test.
=> [FIX] runbot: bug in duplicate module detection

runbot/models/batch.py, runbot/models/dockerfile.py, runbot/models/project.py, runbot/templates/dockerfile.xml, runbot/tests/test_dockerfile.py, runbot/views/bundle_views.xml, runbot/views/dockerfile_views.xml
Since Odoo 14.0, the recommended Ubuntu LTS release is Focal, the
default Docker should be updated accordingly.
A custom template with bionic have to be manually created on runbot
instances that still build Odoo < 14.0.
* Upgrade Chrome version to 90.0.4430.93-1 as this one is currently in
use on our current runbot instance. Just keep in mind that the Odoo
screencast feature does not work anymore since Chrome 88.
* This new Default Docker will not install requirements.txt from the
github odoo master branch anymore. We expect Odoo to run fully with
deb packages only.
... to be continued
TODO check the necessity of:
Awa created a task to remove it.
Did not exists in Stretch nor Bionic ... now exists in [Buster](https://packages.debian.org/buster/python3-pdfminer) and …
=> [IMP] runbot: update docker default for focal

runbot/__manifest__.py, runbot/controllers/frontend.py, runbot/controllers/hook.py, runbot/migrations/13.0.5.1/pre-migration.py, runbot/models/batch.py, runbot/models/branch.py, runbot/models/bundle.py, runbot/tests/common.py, runbot/tests/test_upgrade.py, runbot/views/bundle_views.xml
- Add draft pr management to avoid to trigger code owner on draft pr.
- Add check on falsy config on trigger id (avoid crash, usefull to disable trigger)
- Add extra params on custom trigger to avoid to write specific config every time.
- Trigger a new batch automaticaly when updating target/draft
=> [IMP] add draft pr management + multiple custom fields

requirements.txt
Matplotlib 3.0.2 cannot be `pip installed` on Focal.
=> [FIX] runbot: update matplotlib to focal version

runbot/container.py, runbot/models/build.py, runbot/models/res_config_settings.py, runbot/views/res_config_settings_views.xml
In some conditions, it appears that a containerized build can eat up
all memory of the container host. This leads to disturbance of other
builds as the kernel OOM killer enters the dance.
With this commit, the docker ability to limit memory usage of a
container is used. The OOM killer will choose its victim among the
container processes.
The containers memory limit has to be set in the runbot settings. If not
set, no memory limit is used.
=> [IMP] runbot: limit memory usage of containers

runbot/controllers/hook.py, runbot/models/branch.py, runbot/models/repo.py
When getting pull info, the alive state can be determined easily,
meaning that this field can join the "_compute_branch_infos" familly
Hook was catching some changes made on pr and was conditionnaly updating some fields
and triggering some other operations conditionaly depending on the action flag.
All of the information needed to update the pull info should always be present in the
payload body, meaning that all fields can be updated at once in case some hook was missed,
and additionnal operation can be triggered based on fields changes.
=> [IMP] runbot: cleanup and improve hook

runbot/models/build.py, runbot/models/build_stat.py, runbot/models/runbot.py
Keep running was broken for since 5.0.
This PR fixes the broken logic and adds an index
This PR also remove useless log_access on stats.
=> [FIX] runbot: fix keep_running, and relve log_access on stats

runbot/static/src/js/stats.js, runbot/templates/build_stats.xml
Since the frontend_assets are loaded with `defer="defer"`,
the page sometimes fail with the message:
```
stats.js:212 Uncaught ReferenceError: Chart is not defined
at updateChart (stats.js:212)
at stats.js:158
at XMLHttpRequest.xhttp.onreadystatechange (stats.js:53)
```
This commit checks that Chart is available before tring to render the graph.
Thanks to @kebeclibre for the help.
=> [FIX] runbot: wait for chart.js to be loaded

runbot_merge/__manifest__.py, runbot_merge/migrations/13.0.1.7/pre-migration.py
Draft was added in 82174ae66ee15fa5fdb4d1ad6057c4670e7e2ea8 but turns
out the v13 ORM is not able to create a required column (even when
given a default value), at least for booleans.
So create it by hand.
=> [FIX] runbot_merge: add migration for draft column

runbot_merge/tests/test_basic.py, runbot_merge/views/templates.xml
When a PR is in error, the page only shows "Error:" (well, not right now as a fix to the view was deployed but the fix is not complete so some pages still show that, mostly when a PR can't be staged in the first place).
This is unintended, the page is supposed to report the reason for the PR being in error (mostly the staging failure reason).
=> FIX: display of error message on PR pages

runbot/static/src/js/stats.js
Since the order was changed, the first values are actually the older ones.
This commit inverse newer_build_stats and older_build_stats
values in order to always have the new keys. Before this commit the new
keys where not displayed. A future improvement may be to combine keys
from all builds.
This commit also proposes to give a 0 value if the key did not exist in
the older build. This means that new keys will appear with a big
difference. This is maybe not a good idea and needs some testing. A
better solution would be to search for the first apparition.
=> [FIX] runbot_build_stats

runbot/controllers/frontend.py
When a build error is archived, a linked children with an assigned fixer
may still appear on the error frontend page.
With this commit, old children are not showing up again.
=> [FIX] runbot: prevent showing old fixed build error

forwardport/models/project.py, runbot_merge/models/pull_requests.py, runbot_merge/tests/test_oddities.py
Because sometimes github updates are missed (usually because github
never triggers it), it's possible for the mergebot's view of a PR
description to be incorrect. In that case, the PR may get merged with
the wrong merge message entirely, through no fault of the user.
Since we already fetch the PR info when staging it, there's very
little overhead to checking that the PR message we store is correct
then, and update it if it's not. This means the forward-port's
description should also be correct.
While at it, clean the forward port PR's creation a bit:
- there should always be a message since the title is required on
PRs (only the body can be missing), therefore no need to check that
- as we're adding a bunch of pseudo-headers, there always is a body,
no need for the condition
- inline the …
=> [FIX] runbot_merge: ensure PR description is correct on merge

runbot/models/batch.py, runbot/models/build.py, runbot/models/build_config.py, runbot/models/host.py, runbot/models/runbot.py, runbot/static/src/css/runbot.scss, runbot/templates/dashboard.xml, runbot_builder/builder.py, runbot_builder/leader.py, runbot_builder/tester.py, runbot_builder/tools.py
As for the builder, this give the ability to run the discovery of new
commits and all related logic in a separate process.
This will mainly be usefull to restart frontend without waiting for cron
or restart "leader" without stoping the frontend. This will also be
usefull for optimisation purpose.
=> [IMP] runbot: create a separate process for cron

runbot/models/branch.py, runbot/models/repo.py, runbot/views/repo_views.xml
Right now single version repo like upgrade are managed using
a regex to limit name prefix, this avoid grouping branches when
mergebot wont be able to merge them together but the ci can be painfull
since the branch needs to be renamed (closing existing pr) or a manual
operation to move the branch into a new bundle must be performed.
This commit proposes to replace the forbidden_regex mechanism with
an explicit single_version mechanism.
In this case the reference name will be automatically prefixes with
the version. The name is also suffixed with `-()` to indicate that some
magic was applied.
=> [IMP] runbot: add single branch repo

runbot/models/branch.py, runbot/models/host.py, runbot/models/repo.py, runbot/templates/dockerfile.xml, runbot/views/repo_views.xml, runbot_builder/tools.py
Since odoo/odoo@3d6043a7356b90e5a69a5b535ec6c651d0860711 the controll file can contain fallbacks `dep1 | dep2 | dep3`.
Taking the first column will work in most cases.
=> [FIX] runbot: manage or in debian/controll

runbot/models/commit.py
When a git archive fails, the partially exported source tree is left in
place. If another builds tries to use the same commit, the tree is not
exported anymore as the directory exists. This leads to non
deterministic behaviors.
=> [FIX] runbot: removing failed git export

runbot/models/build.py, runbot/models/res_config_settings.py, runbot/views/res_config_settings_views.xml
When a build is garbage collected and the local folders are cleaned, the
log files are kept to allow build errors investigations.
With this commit, a full local cleanup will be done 365 days after the
garbage collect.  This means that the build dir will be completely
removed.  The default number of days can be tweaked with the
`runbot.full_gc_days` ir.config_parameter.
Also, the _local_cleanup method can be called with a `full` boolean
parameter to force a full cleanup. e.g.: when called in a config step.
=> [IMP] runbot: fully garbage collect old builds

runbot/models/build.py, runbot/models/commit.py, runbot/models/runbot.py, runbot/security/ir.model.access.csv
Source cleanup will check in multiple place for potentially used
commits. This maked the cleanup logic complex, plus limit the usable
commits in python steps. The current use case is to export the mergebase
commits.
The poposed solution is to save the exported commit and clean this list
when the build is done. All commit in this list cannot be cleaned.
=> [IMP] runbot: commit exports 

runbot/common.py, runbot/tests/test_event.py
The `utils.escape` utility was deprecated in werkzeug 2.0.0, so it can
be replaced with our `html_escape` which is itself `markupsafe.escape`.
Also, with this change, the double quotes are now escaped in `&#34;`
instead of `&quot;`, so we fix the test too.
=> [FIX] runbot: avoid werkzeug deprecated escape

runbot/models/build_error.py
When an error is assigned to a team and the error is a child of another
one, the two errors are displayed on the team dashboard and adds
confusion.
=> [FIX] runbot: avoid children in team errors

runbot/models/batch.py, runbot/models/build.py, runbot/models/commit.py, runbot/models/repo.py, runbot/models/runbot.py, runbot/views/repo_views.xml
The status are currently sent by leader when build are created and by
workers on post_commit.
If the leader fails during the preparing of a batch (while creating
builds) the transaction is rollbacked and the status are send again.
The number of status to send makes it quite slow, making the transaction
longuer, and the retry even more expensive. This leads to preparing time
being quite important, sometimes ten minutes after many retries.
This commit proposes to send status in another dedicated transaction.
Since status are sent in batch, we can also try to use a unique session,
and uniquify commit+context status.
This allows to remove the postcommit logic
A further improvement would be to wait before sending status in order to
skip the pending status if the build is verry fast.
An option …
=> [IMP] runbot: status management

runbot/models/repo.py, runbot/tests/common.py, runbot/tests/test_repo.py
Regarding the number of refs in odoo repo (arround 18 million at this
time), the parsing of the date was significant when filtering old refs.
Using unix time allows a direct comparaison without parsing the date,
and improved performance, going from ~7 seconds to ~1.3 seconds.
=> [IMP] runbot: speedup get_refs

requirements.txt, runbot/container.py, runbot/models/host.py, runbot/tests/test_dockerfile.py
While using the docker cli as a subprocess was KISS and convenient,
the python Docker SDK is mature, easy to use, available as a Debian
package and much more powerful.
It will permit to monitor the containers memory consumption and will
help to spot memory leaks.
=> [IMP] runbot: use docker python lib

runbot/container.py, runbot/models/build.py
In bd4cf76b7 a new argument `--progress-bar off` was added to the pip
command line. Unfortunately, it appears that this argument is not
available in some pip versions, typically the one from Ubuntu Bionic
(9.0.1) [0]. The argument appeared in version 10.0.0 [1].
Also, in the DockerFile, we allow the user to use `sudo` for
`/usr/bin/pip3` and the main reason for that was to avoid having `pip`
to re-install the package that are pre-installed by the distribution
package manager.
That said, it appears that since pip 10.0.0 when installing packages
locally for the user, pip now properly detects distribution installed
packages.
So, as the solution to fix the progress bar issue is to upgrade pip to a
newer version, we can take advantage of it to get rid of the `sudo`.
Besides the fact that …
=> [FIX] runbot: avoid sudo when using pip

runbot/templates/utils.xml
Because the login link redirected to `/`, when logging in the user would have
to re-navigate to their previous page unless they'd remembered this issue and
kept the original page around.
Fix this because it's annoying and dumb: we know our URL when rendering
templates, so we can redirect back there after login.
Consideration: this could also be done on logout, however it seems likely that
in that case the original page is "privileged" and when coming back we'd just
get an access error. So don't do it for now.
=> [FIX] runbot: redirect to current page after login

runbot/models/commit.py
When exporting a commit, it will be useful to freeze the modification
time of the exported files. The idea behind that is to pre-generate
bundles at the install time of the Odoo instances, that way when running
the post install tests, the bundles does not have to be generated for
each test.
=> [IMP] runbot: freeze files modification time at export

runbot/container.py
In some rare cases, a docker container has a status of exited, removed
or in removal and the `end-`file has been written right after the code
checked the existence of the file.
To mitigate the issue, this commit checks the `end-` file existence
after the container status have been checked. That way, if the file
exists we can be pretty confident that the build really ended.
=> [FIX] runbot: mitigate docker status race condition

runbot/__manifest__.py, runbot/controllers/frontend.py, runbot/static/src/css/runbot.css, runbot/templates/build_error.xml
Before this commit, the build errors page was neither sortable neither
filterable.
This commit adds a way to filter by:
- all
- unassigned
- seen more than once
It also allows to sort by:
- last seen
- nb seen
Typical need is to sort by nb seen and filter out the only seen once to
be able to figure which one is supposed to be checked in priority.
See result: https://watch.screencastify.com/v/L3x0qnuSgZOMQUjYDKk3
=> [IMP] runbot: add sort and filter capability on the build error page

runbot/models/runbot.py
The sleep 1 was ok with a few builder bur regarding the number of
request on the database when no build are running, this become
problematic.
An ideal solution would be to detect if
-> me managed some testing build
-> There is load (pendings)
In both case, we don't want to sleep to much.
In other cases, we may want to wait a little longer.
A simple quick fix will just wait longer in all cases.
=> [FIX] runbot: reduce load when builder are idle

runbot/models/build.py, runbot/tests/test_build.py
When the builds directory is filled with a lot of build directories (around 100000) the garbage collection process may take up to 2 minutes. The root cause is that each build directory is scanned to clean it up even if it was already cleaned.
With this commit, a stamp file is used to mark directories that were already garbage collected.
=> [IMP] runbot: speedup build garbage collecting

runbot/common.py, runbot/data/runbot_data.xml, runbot/models/build_config.py, runbot/tests/common.py, runbot/tests/test_build_config_step.py, runbot/tests/test_cron.py, runbot/tests/test_repo.py
Various fixes:
* fix broken custom build wizard that was not using the number_build parameter anymore
* use a real line feed in an xml file instead of a literal \n that broke odoorc file
*  use gethostname instead of getfqdn
=> 15.0 runbot varfixes moc

runbot/controllers/hook.py, runbot/models/branch.py, runbot/models/build_error.py, runbot/views/build_error_views.xml, runbot/views/menus.xml
The build error view was unstructured and contains to much information.
This commit organize fields in groups and also validate some modification on records in order to avoid build error manager to disable test-tags by mistake.
An error cannot be deactivated if it appeared less than 24 hours ago to avoid disabling a non forxardported pr that will fail the next nightly generating another build error.
Test tags can only be added or removed by administrators.
Also adds a menu for easier User managerment
Also fixed the dname search and display.
=> [IMP] runbot: improve build_error management

runbot/__manifest__.py, runbot/common.py, runbot/data/runbot_data.xml, runbot/migrations/15.0.5.2/pre-migration.py, runbot/models/build.py, runbot/models/event.py, runbot/models/host.py, runbot/models/res_config_settings.py, runbot/models/runbot.py, runbot/tests/__init__.py, runbot/tests/common.py, runbot/tests/test_build.py, runbot/tests/test_cron.py, runbot/tests/test_event.py, runbot/tests/test_host.py, runbot/tests/test_schedule.py, runbot/tests/test_upgrade.py, runbot/views/res_config_settings_views.xml, runbot_builder/builder.py
When the number of runbot builder is growing, the concurency for inserting logs increase drastically.
This PR is an attempt to mitigate this issue by allowing runbot builds to insert logs into a local database instead of the one from the runbot leader.
After each loop turn, it's now the builder that will insert the logs directly into the leader database.
=> [IMP] runbot: let the build insert logs into local database

runbot/security/runbot_security.xml, runbot/templates/bundle.xml
Force new batch buttons can be sometimes confusing for user. Creating a group to show this button for advanced user only will help avoiding useless new batch when it's not needed.
New batch is only needed:
- to create a new slot when a new trigger is added/modified through a custom trigger
- take last databases into account for upgrades, mainly when backporting a new field or strange usually forbiden operations
- avoiding to need to push again to rebase when a r+ was added on one pr but one of them needs to be rebased or adapted.
Thos case are unusuall but the button is used most of the time thinking this is a kind or rebuild or maybe it will rebase and push the branch on the pr. Only user with basic knowledge of when it is needed should have access to these buttons.
=> [IMP] runbot: hide some buttons

runbot/__manifest__.py, runbot/common.py, runbot/data/runbot_data.xml, runbot/models/build_config_codeowner.py, runbot/models/build_error.py, runbot/models/bundle.py, runbot/models/codeowner.py, runbot/models/commit.py, runbot/models/project.py, runbot/models/repo.py, runbot/models/res_config_settings.py, runbot/models/res_users.py, runbot/models/team.py, runbot/static/src/js/fields.js, runbot/tests/test_build_config_step.py, runbot/tests/test_build_error.py, runbot/views/build_error_views.xml, runbot/views/bundle_views.xml, runbot/views/codeowner_views.xml, runbot/views/dashboard_views.xml, runbot/views/repo_views.xml, runbot/views/res_config_settings_views.xml, runbot/views/user.xml
This idea was postpone for a while since this was most a mergebot responsability but having the github login of the user will help for some team feature requests.
The main one is to only ping a team if the pr was not opened by a member of the team. We want to let the team manager manage that as much as possible so the team manager group will be able to write the user github login (as well as the user himself) and add a list of non user github_login to consider if not all user have a account on runbot.
This commit also improves the views for team managers.
=> [IMP] runbot: better team ownership management

runbot/data/runbot_build_config_data.xml, runbot/models/build.py, runbot/models/build_config.py
Since the custom create was introduced, if a config is added in the config data of a create step, the config can be dynamic. If the given config contains a create step, this become recursive.
This is fixed in this commit by:
- Only taking a custom config if the base config as no create_config_id This means that the only elligible config should be the Custom Multi since it was adapted for that.
- Checking the parent_path depth in add_child. This will also work for python config.
- Consuming the params when adding the child
=> [FIX] runbot: avoid recursion in create steps

runbot/models/runbot.py
Right now, multiple build are read when managing build to schedule.
This is not usefull since the transaction is commited between each of them. Moreover, the read build can be written from another host adding another possibility to have a conccurent update.
Removing the prefetch_ids may help a little.
=> [IMP] runbot: reduce concurrency

runbot/models/batch.py, runbot/models/build.py, runbot/models/build_config_codeowner.py, runbot/models/bundle.py, runbot/models/runbot.py
The main idea is to allow some build to use an extra slot from all host if a bundle is in priority mode.
This is mainly for quick step debuging, mainly when modifying python steps when the runbot is fully loaded.
This will also be usefull to concurrency test, by starting a build on each host at the same time, even when some host are already fully loaded
=> [IMP] runbot: add priority queue for debuging

runbot/models/repo.py
Right now, a branch with a numerical name will be added to the database, but it can conflict with pr since the name of a pr is a number. This means that a unique (name, repo_id) constraints can be broken. We could use the 'is_pr' in the unicity constraints to avoid this issue but searching on branch name will give confusing result if some of them can be numerical.
Moreover, a runbot branch name should start with the version name meaning that a numerical branch name was a bad idea from the begining.
=> [FIX] runbot: filter numerical branch names

runbot_builder/builder.py, runbot_builder/tools.py
At this moment it's difficult to monitor a build cpu and memory usage. This must be done from outside the container to avoid to kill the cat by opening the box.
This commit adds a daemonic thread launched by the builder. This thread will read the memory and cpu stats of the running dockers and report their stats in a log file into the logs directory of the builds.
The log file format is made to be easily mixed with the build logs and spot memory leaks or cpu overload during builds.
=> [IMP] runbot: add a monitoring tool to the builder

runbot/data/runbot_data.xml, runbot/models/repo.py, runbot/models/res_config_settings.py, runbot/views/res_config_settings_views.xml
The auto disable host is mainly usefull when there are a lot of host for well configured repositories.
If for any reason a repo is corrupted on one host, this host will be disabled until a manual intervention cleans the repo.
For other cases, where thjere are many repositories with not so many host, it is most likely that a fetch will fail because of an invalid repository configuration. Disabling the host in this case is not a good idea.
With this commit, a settings allows to enable or disable this feature.
=> [IMP] runbot: make disable host configurable

runbot/models/build_error.py, runbot/views/build_error_views.xml
When an error is linked to another one, we don't expect it  to appear on team and user dashboard. When adding a parent, this will transfer the responsible from the child to the parent when applicable.
=> [IMP] runbot: automatically transfer responsible

runbot/models/repo.py, runbot/tests/test_build_config_step.py, runbot/tests/test_repo.py
Since removeprefix was not available in ubuntu 20.04, a easier alternative using rebase was used.
The initial assumption was that the prefix would look like `odoo/addons/` and won't be in the filename.
When the repo is enterprise, the prefix is `enterprise/` meaning that module name ending with `enterprise` will be truncated
`repo._get_module('enterprise/mail_enterprise/static/src/widgets/form_renderer/form_renderer.js')`
will output
`mail_static`
=> [FIX] runbot: get_module remove prefix

runbot/models/build_error.py, runbot/tests/test_build_error.py
When parenting a build error, if a test_tag is set on it, the tag is transferred to the parent and cleared to an empty string. In that case, a single `-` appears in the disabling tags and leads to an apocalyptic situation ... the runbot builds don't run any tests.
With this commit, the test_tags is set to `False`.
=> [FIX] runbot: avoid empty negative test tags

runbot_builder/tools.py
Currently, the addons_path is intuited from the location of the script, with the assumption that the only custom addons path will be runbot itself.
This commit introduces an addons_path parameter to support custom deployments. If the parameter is not set, the existing behaviour is unchanged.
=> [IMP] runbot_builder: support addons_path parameter

runbot/models/build_config.py
This was missing to make python (and other non docker) steps really blazing fast
=> [FIX] runbot: fix missing return

runbot/models/batch.py, runbot/models/build.py
When a build is created, it will first check for another build having the same params. It is usually a good idea to avoid to much load. In some case, a build can be found, but a killed one.
This is not what we want:
The first scenario is to consecutive force push,
commit1 -> commit2 -> commit1
The build of commit1 may be killed because of commit2, then when forcepushing commit1 again, it will be linked to a killed build.
A even more problematic problem was discovered because of a delay In odoo/odoo repo hook. An odoo-dev/odoo 16.0-... branch was discovered first using this commit, and a build was created.
Then, the branch was forcedpushed and the build was killed. Finally, the 16.0 commit was discovered, and was linked to the killed build. This was mainly an issue because the build was a …
=> [IMP] runbot: avoid link to killed build

runbot_merge/models/pull_requests.py, runbot_merge/views/templates.xml
The mergebot page become a bit slow with the years, it is time to make small optimisation to speed up thinks a little.
Note: all changes where applied modifying the views or adding index by hand. There is still room for improvement but it would need more in depth refactoring, mainly adding specialized computed fields to enable a better batching.
The first issue was using branch.staging_ids
branch.staging_ids.sorted(lambda s: s.staged_at, reverse=True)[:6]
The number of staging_ids is increasing and prefetching + sorting all of them is slow.
The proposed solution is to replace it by a search, not ideal, a specialized compute field may be a good idea, but this is a quick fix that can be done editing a view.
branch.env['runbot_merge.stagings'].search([('target', '=', …
=> [IMP] runbot_merge: speedup frontend page

runbot/models/host.py
In some case, a build can add a lot of info in a log, there is already a limit to the number of entry but not to the size of an entry. This will limit the database usage in case of mistake/abuse.
=> [FIX] runbot: limit max log size

runbot/controllers/hook.py, runbot/models/build.py, runbot/models/runbot.py
The _kill method was called in multiple case, usually when something wrong happen:
- exception initiating pending
- kill requested manually
- testing time exceeded
- exception running a job
- ...
But it will also be called when killing a running build.
It was usually not an issue since the status remains the same, but it is not true if the same commit is used in two build, the new one is green, the old one is red (enterprise commit remaining the same but community commit changed as an example)
In this situation, the enterprise commit may receive the red ci from the old build while the last one is green.
Since with the last version, the github status responsibility is left to write method, this github status is not useful anymore, updating the state and result is enough.
This commit also …
=> [FIX] runbot: avoid sending status on running kill

runbot/models/batch.py, runbot/models/build_config.py
Since all versions will have a defined dockerfile, the project one will alway be ignored. The idea here is that for a project, we may definea default dockerfile_id so that we don't have to set it on all bundle to make it work.
=> [FIX] runbot: fix dockerfile choice order

runbot/models/build.py
When the runbot tries to drop a local database, if the that raises an exception, it goes in a loop failure. It mays happen for example if someone forgot to close a psql during an investigation :-)
With this commit, the exceptions are catched and at least the database name is logged.
=> [FIX] runbot: catch exceptions during db drop

runbot/views/build_error_views.xml, runbot/views/bundle_views.xml, runbot/views/codeowner_views.xml, runbot/views/config_views.xml, runbot/views/dashboard_views.xml, runbot/views/dockerfile_views.xml, runbot/views/host_views.xml
The `oe_chatter` div must be defined after a sheet, otherwise two chatters are visible on the form. One bellow and one on the right side.
=> [FIX] runbot: chatter must be after sheet

runbot/models/build_config.py, runbot/models/bundle.py, runbot/models/custom_trigger.py, runbot/models/repo.py, runbot/tests/common.py, runbot/tests/test_build_config_step.py, runbot/views/bundle_views.xml, runbot/views/custom_trigger_wizard_views.xml, runbot/views/repo_views.xml
One of the most common custom trigger is to restore a build before starting some test, either to create a multibuild or make the execution and debug of some test faster.
It is somethimes tedious to use because we need to give an url of a build to restore. This build must correspond to the right commits, must still exixt, ... this means that the dump url must be adapted everytime a branch is rebased.
The way the dump_url is defined is by going on the last batch, following the link to the `base_reference_batch_id`, finding a slot corresponding to the right repo set, (ex: Custom enterprise -> enterprise), and copying the dump_url in this build.
The base_reference_batch_id is eay to automated but we have to find the right trigger, this is now a parameter of the custom trigger wizard. There …
=> [IMP] runbot: add auto restore for custom trigger

runbot/models/event.py
Since odoo/odoo@a01e8b5232 this hack should not be necessary anymore.
=> [FIX] runbot: remove search_count hack

runbot/container.py
When investigating kernel logs e.g.: for finding oom killed containers, the kernel does not log the name of the incriminated container but only the id. With this commit the runbot will also log the container short id which is enough to correlate the logs.
=> [IMP] runbot: log container short id

runbot/templates/bundle.xml
Even if we prefer to avoid this use case, some devs like to use the same branch for multiple pr. This change allows to reopen a pr once one is closed.
=> [IMP] runbot: allow pr creation on closed pr

runbot/models/build.py, runbot/templates/utils.xml
A check was add to avoid to wakeup a child if there is a parent database Most of the time, it was a mistake.
In some case it can be legit, if the parent only creates subbuid without installing any database.
This commit fixes that by allowing to wake up child if the parent has no database.
=> [FIX] runbot: wakeup child without parent db

runbot/models/batch.py, runbot/models/bundle.py, runbot/models/project.py, runbot/views/bundle_views.xml
Using dev branch from foreign project to fill missing commits looks like a bad idea, mainly because the lifecycle of the branches is not the same
In some case, it can be useful to allow that to test a branch with a future change in the base project that will be needed to make the branch work. As an example introducing a small api change in odoo to make an override easier, or introducing a module that may be needed to use the feature.
This commit changes that by allowing to configure on the project or bundle if we allow to use foreign bundle as reference *before* checking the base bundle.
=> [IMP] runbot: allow to use dev foreign branches

runbot/models/build_error.py, runbot/models/ir_logging.py, runbot/tests/test_build_error.py, runbot/views/build_error_views.xml
- when build errors are re-cleaned, they are also merged if the recomputed fingerprints are matching
- Also fixes the ir_logging compute that associate a build error so that the active build error is preferred over an inactive one.
- Allow to choose the replacement string in cleaning regexes
- optionally shows the fingerprint column in build error list view
=> [IMP] runbot: improve build error cleaning action

runbot/controllers/frontend.py, runbot/models/build_error.py, runbot/templates/build_error.xml, runbot/views/build_error_views.xml
When filtering the build error tree view based on the versions equality,
the results may not be what you expect.
e.g.: searching for `versions is equal to 16.0` gives the errors that
appeared in `16.0` (hopefully) but also those which appeared in other
versions too.
With this commit, this search will give the errors that appeared in the
specified version only. When the user wants to list errors that appeared
in `16.0` and other versions too, he has to use the `contains 16.0`
criteria.
=> 16.0 search single version moc

runbot/models/build_error.py
Since c6f9d1f0c a new model was added to link build errors and builds. The _search_version and _search_trigger_ids were not adapted to work with this new model.
=> [FIX] runbot: adapt build error search for link model

runbot/__manifest__.py, runbot/models/build_error.py, runbot/tests/test_build_error.py
Because of a bad dependency on the compute, the first seen date and last seen date are not always updated.
e.g.: a new build is scanned and a build is added to a linked error, the parent error seen dates are not updated.
A test is added to reproduce the case.
=> [FIX] runbot: fix errors first and last seen dates

runbot/controllers/frontend.py, runbot/models/build.py, runbot/models/commit.py, runbot/models/project.py, runbot/models/repo.py, runbot/security/ir.model.access.csv, runbot/tests/test_build.py, runbot/views/bundle_views.xml, runbot/views/repo_views.xml
When using a repo as a dependency for another trigger, the default module filter for a repo is not always ideal
As an example, when using odoo as a dependency for another repo, we may only want to install the module from the new repo.
This iss done right now by creating a custom config but this lead to duplicates config and steps only to customize the module to install.
This commit proposes a new model to store the filters.
Note that this may be used later as module blacklist on repo too.
=> [IMP] runbot: allow to customize repo filters from
