- runbot/models/build.py
- runbot/models/repo.py
- Decode error
- iteritems is not a attribute of dictionary anymore
> [FIX] runbot: py3 fixes

- runbot/models/build.py
Actually, when a build is a duplicate of another build, its github status is not updated.
e.g. a pull request may not have a github status but its corresponding
branch have a gtihub status.
With this commit, all builds will have its github status updated based
on the corresponding build status.
Thanks for your help @xmo-odoo
> [FIX] runbot: update github status on duplicates too

- runbot/templates/build.xml
Add title and aria-labels on buttons to describe them.
> [IMP] Improve a11y and usability with titles and aria-labels on buttons

- runbot/__manifest__.py
- runbot/controllers/frontend.py
- runbot/models/build.py
- runbot/models/repo.py
- runbot/templates/build.xml
Force a rebuild when a reverse dependency commit is detected.
e.g. when a new commit in community is fetched, force a rebuild of the latest commit in enterprise.
Use case: make it easier to detect a commit that makes the tests fail in another depending repository
> Master trigger enterprise build moc

- runbot/controllers/frontend.py
- runbot/templates/dashboard.xml
- runbot/templates/frontend.xml
Preview (screenshot TTL: 1 month)
> [IMP] runbot: color "pending" tag accordingly to some limits

- runbot/models/build.py
When the Odoo instances are spawned for tests, they have a time limit
set on their CPU usage. This limit is hard-coded in the _spawn method
calls.
As the number of tests are increasing, their duration increases too.
As this limit is inherited by subprocesses, if a phantomjs test
last too long, the test is killed alone.
Finally, when the coverage is enabled, the tests duration is
approximately increases of 1.5 times.
With this commit, the cpu_limit of the two main tests jobs are
increased. An ir.config_parameter can optionaly be used to tweak this
limit without changing the code. When the coverage is used, the
cpu_limit is increased.
> [IMP] runbot: increase cpu_limit

- runbot/models/build.py
When a build with coverage is killed during the tests, the coverage
result is set to 100%.
With this commit, coverage result is verbosely skipped if the coverage
file does not exists.
> [FIX] runbot: handle faulty coverage

- runbot/controllers/frontend.py
With this feature you can easily search your branch and branch from your team; or your features...
Eg: jke|-website or -jke|-rde|-qsm|...
> [IMP] runbot: allow to search multi terms with |

- runbot_merge/models/pull_requests.py
- runbot_merge/tests/test_basic.py
If the message already contains the pr number, no need to add it again
> [FIX] runbot_merge: avoid double closes message

- runbot/models/build.py
When a commit is built serveral times, each time the status is updated, a
request is sent to github for each build.
As a side effect, if the first build is a failure and the last one a
success, github is wrongly updated to failure.
This bug is particulary annoying on PR in conjunction with the
runbot_merge, preventing the PR to be merged even after several
rebuild.
With this commit, only the latest build per repository is used to update
the github status. The amount of github status updates is also reduced.
> [FIX] runbot: reduce the amount of github status

- runbot/__init__.py
- runbot/__manifest__.py
- runbot/common.py
- runbot/container.py
- runbot/data/Dockerfile
- runbot/models/build.py
- runbot_cla/runbot.py
Use docker to containerize builds.
> [IMP] runbot: containerize builds

- runbot/models/build.py
Useless merge-base command is causing timeouts on runbots.
As this part never worked for a few years, this code is removed.
> [FIX] runbot: remove common ancestor case

- runbot/container.py
- runbot/models/build.py
When the docker_run function is called, the odoo command is decorated
with a pip command to install required packages.
This pollute the docker_run function if a runbot job_ method wants to
use docker for something else that starting an odoo instance (like
pg_dump) for example.
With this commit, command modification is made in an optional helper
function named build_odoo_cmd.
the docker_run function now needs the command to run as a string instead
of a list of odoo cmd and its parameters.
> [IMP] runbot: detach odoo command from docker_run

- runbot_merge/models/pull_requests.py
Replace the arbitrary sleep after having staged a head by checking for the head to be visible to regular git client through the HTTP v1 "smart" protocol: `$GIT_URL/info/refs?service=git-upload-pack` returns a listing of all the repo's refs and should be what regular git clients see (and the first thing they fetch) when fetching a repo.
Also alter the semantics slightly: if a head is never seen, the staging now fails (rather than carrying on blindly with staging the dependents), though it's not rolled back (maybe it should be?)
Performs one check immediately, because for smaller repositories the update is essentially instantaneous.
> When staging, wait for the new head to be visible at the repo-level before staging the next repo

- runbot/controllers/frontend.py
On a par with `/glances` page.
> [IMP] runbot: sort sticky branches chronologically

- runbot/models/build.py
- runbot/tests/test_build.py
And add tests to avoid regression.
> [FIX] runbot: adapt build write method to api multi

- runbot/data/Dockerfile
- runbot/models/build.py
- runbot/models/build_config.py
Various commits to improve the _run_python job and ease the migration scripts integration.
> Master build config python more moc

- runbot/controllers/frontend.py
- runbot/models/res_config_settings.py
- runbot/templates/frontend.xml
- runbot/views/res_config_settings_views.xml
Instead of spamming people when a runbot upgrade will occur why not use a custom banner message.
> [IMP] runbot: add optional warning message on frontend

- runbot/models/build.py
- runbot/models/repo.py
- runbot/tests/test_repo.py
When updating github statuses, it happens that we face a "Bad gateway"
from github. In that case, the error is logged in the runbot logs and
that's it. As a consequence, when the runbot_merge is waiting status for
the staging branch and this kind of error occurs, the runbot_merge
timeouts and the users vainly search the reason.
With this commit, the runbot tries to update the status at least twice.
If it fails, an INFO message is logged on the build itself.
> [FIX] runbot: try to update github status multiple times

- runbot_merge/models/pull_requests.py
Allows merging a fix for e.g. a common false positive during a split
but without cancelling a staging which might just pass (you never
know).
> [IMP] runbot_merge: p=1 > split

- runbot_merge/models/pull_requests.py
- runbot_merge/tests/test_basic.py
Also add test for it & feedback of an approved PR failing CI, and fix corner case with it (might not send a warning immediately on CI failure depending on status requirement ordering).
> Send feedback when approving PR which failed CI

- runbot/common.py
Wait 2 unit before change.
42s ... 60s ... 119s 2m ... 60m ... 119m 2h ... 24h ... 47h 2d ...
> [IMP] runbot: more human time display

- runbot/models/build.py
> [FIX] runbot: typo (closet -> closest)

- runbot_merge/models/pull_requests.py
Github constrains a single issue (/PR) number per repository, having different targets does not allow two PRs to share a number.
See #169 (which this doesn't quite fix, but it should break upward of having created two PRs under the same number).
> Fix indexing of PR objects

- runbot_merge/models/pull_requests.py
- runbot_merge/tests/test_basic.py
> Less restrictive commands matching

- conftest.py
- runbot_merge/controllers/__init__.py
- runbot_merge/models/pull_requests.py
- runbot_merge/tests/remote.py
* testing bits to global conftest so they can be reused
* improves nginx handling so it can be used concurrently in multiple test sessions
* extract creation of PR object & improve PR printing
> Master improve tests xmo

- forwardport/__init__.py
- forwardport/__manifest__.py
- forwardport/data/crons.xml
- forwardport/data/security.xml
- forwardport/data/views.xml
- forwardport/models/__init__.py
- forwardport/models/forwardport.py
- forwardport/models/project.py
- forwardport/tests/conftest.py
- forwardport/tests/test_simple.py
- forwardport/tests/test_weird.py
- forwardport/tests/utils.py
- runbot_merge/controllers/__init__.py
- runbot_merge/models/pull_requests.py
- runbot_merge/tests/fake_github/__init__.py
- runbot_merge/tests/fake_github/git.py
- runbot_merge/tests/remote.py
- runbot_merge/tests/test_basic.py
* still need to decide what user we'll be using. code may need to be modified if we decide that the fp user is the same as the mergebot's: FP currently uses "r+" as command, which would conflict. Also might need to create a new token as as FP uses somewhat different rights than mergebot.
* there's a bunch of todos & fixmes left in the code, they should be of low consequences
> Simonis bot

- runbot/models/build_error.py
- runbot/tests/test_build_error.py
When a build_error active field is changed, the onchange leads to a
traceback. Anyway, the onchange was not a good idea as it only reflects
UI changes.
With this commit, the write method is overwritten to change the
child_ids active fields too. Also, the active_test context is used to
correctly compute the childs_ids and children_build_ids.
A test is also added for all that.
> [FIX] runbot: fix build_error active field changes

- runbot/container.py
- runbot/models/build.py
- runbot/models/build_config.py
- runbot/models/event.py
- runbot/templates/build.xml
- runbot/tests/test_build_config_step.py
Introduce a new 'final' cmd part in order to execute it
even if build fails.
> [IMP] runbot: dump database at the end of step

- runbot/models/build_config.py
Current dump version doesn't include filestore. This new
version adds the filestore trying to match odoo backup format
in order to ease restore.
manifest.json file is not create since it isn't usefull,
but an info.json is added, with build info.
> [IMP] runbot: improve db dump

- runbot/models/repo.py
As the --upgrade-paths options does not work as expected in Odoo, a
symbolic link as to be created in odoo/addons/base/maintenance pointing
to the migration scripts.
The runbot uses Docker read-only volumes to access the sources that are
shared between builds, preventing the creation of such a link.
With this commit, a symbolic link is created right after the export of a
commit only when the repo is a "server" repo.
This link is broken outside of the Docker volumes but uses the mount
points of the sources inside the container.
Two ir.config_parameter's are used to enable and configure this feature:
* runbot_migration_ln: the relative path where the link should be placed
(typically odoo/addons/base/maintenance)
* runbot_migration_repo_id: the id of the migration scripts repo, used
to …
> [HACK] runbot: create a broken symlink in all server sources

- runbot/models/branch.py
- runbot/models/repo.py
- runbot/views/branch_views.xml
When a repo is set to "no_build", there is no way to force a branch to
build from the backend.
With this commit, a button is added on a branch form to ask rebuild of the
branch, even when the repo is set to "no_build".
> [IMP] runbot: allow to rebuild a branch

- runbot_builder/builder.py
* If an excpetion occurs during the main loop, the builder crashes. With
this commit, the main_loop is in a try/catch.
Also:
* remove unused imports
* move the first log after the Odoo import because Odoo changes the
process timezone to UTC
> [FIX] runbot: catch exceptions during main loop

- runbot/models/build.py
- runbot/templates/build.xml
* Keep tests directory in build path.
* Restore the forgotten Separator
> Master runbot keep tests dir moc

- forwardport/data/security.xml
- forwardport/models/project.py
- runbot_merge/models/pull_requests.py
- runbot_merge/models/res_partner.py
- runbot_merge/static/scss/runbot_merge.scss
- runbot_merge/views/templates.xml
Since the runbot was migrated we might as well migrate those two as well.
> Master mergebot migration

- runbot/data/Dockerfile
The fix odoo/odoo#45347 was merged two weeks ago, it's now time to
deploy on runbot.
> [IMP] runbot: bump Google Chrome version to 80

- forwardport/models/project.py
e9e08fec3c2a64a74e7171b4a8ee5f989f1d8733 attempted to fix the issue
but obviously failed as it still occurs: when creating a PR through
the API, it's possible that the webhook gets triggered fast enough the
transaction creating the PR from the webhook commits before we get
around to creating our own PR from the API call. In which case the
forward port process aborts.
The process is re-run later on and generally succeeds fully, but we're
left with a dangling PR we created but couldn't do anything with as
its use broke.
This issue seems to be getting more frequent so it's becoming quite
important to fix it. Therefore we give our Raging Bull a Big Gun and
now he has 20 attack *cough cough* we lock the bloody table down
tight (only allow concurrent `SELECT`) until we've got the PR back and …
> [FIX] forwardport: race condition on PR creation

- runbot/models/repo.py
- runbot/tests/test_repo.py
Sometimes, it happens that a `git fetch` fails with an error code 128
for example. When this happens, the runbot host is immediately disabled.
During investigations of such cases, we found that simply retrying the
fetch command works.
With this commit, the fetch command is tried 5 times with an increasing
delay before deciding to disable the runbot host.
> [IMP] runbot: try to fetch multiple times before disabling

- runbot/models/build.py
Runbot can send status multiple time for the same hash:
- if transaction fails in scheduler and is retried
- if multiple subbuild are failing
Leading to multiple issues:
- when github receive more than one failure status, mergebot will
be notified multiple times and send multiple mail (for forward ports mainly)
- github will answer `422 Unprocessable Entity for url...` after
1000 status.
This fix proposes to limit number of status:
- By avoiding to send status for orphan build (parent status will never change)
- By storing last send status to avoid to notify multiple time
- By sending status post commit to avoid to contact  github in case of failure.
This will also slightly reduce transaction time by removing an http request.
> [FIX] runbot: send status only once.

- forwardport/models/project.py
Given a PR batch getting forward-ported together, if one of the PRs
has a conflict the others should be considered "in conflict" as well,
and should have a note pointing in that direction and indicating that
the PR should be approved the normal way eventually. Which they do.
However, the message is confusing as it gets bolted on the normal
non-conflicting message, either noting that it's part of a chain
or (worse because it gives conflicting indication) the "terminal"
message recommending using the forwardbot to approve of the entire
chain.
I've no idea why I did it that way instead of just adding a case to
the conditional, and the commit message provides no indication. But
perform that change, it seems innocuous, hopefully there weren't good
reasons I forgot about for doing it the other …
> [FIX] forwardport: incorrect / misleading conflict message

- runbot/models/build_config.py
- runbot/models/host.py
- runbot/templates/utils.xml
- execute coverage results in case of failure
- fix coverage links
- use coverage directly
> [IMP] runbot: improve coverage

- runbot/controllers/frontend.py
- runbot/data/build_parse.xml
- runbot/models/build.py
- runbot/models/build_error.py
- runbot/models/event.py
- runbot/static/src/js/runbot.js
- runbot/templates/build_error.xml
- runbot/templates/bundle.xml
- runbot/templates/frontend.xml
- runbot/templates/utils.xml
- runbot/views/build_error_views.xml
* fix the build error creation form (not often used but annoying)
* redirects to the build error after a build scan or a log scan
* shows all assigned errors on the build error page
> [IMP] runbot: improve build error management

- runbot/models/build.py
- runbot/models/build_error.py
- runbot/models/runbot.py
- runbot/models/upgrade.py
- runbot/templates/build.xml
- runbot/templates/build_error.xml
- runbot/templates/bundle.xml
- runbot/templates/commit.xml
- runbot/templates/utils.xml
- fix missing bacth references on builds
- fix group on action buttons
> [FIX] runbot: various view fixes

- runbot/container.py
- runbot/controllers/frontend.py
- runbot/controllers/hook.py
- runbot/models/build.py
- runbot/models/commit.py
- runbot/models/host.py
- runbot/models/runbot.py
- runbot/tests/test_build.py
runbot servers are running with a log-level debug in order to have usefull
debug information, but this also causes some noise comming from odoo.
This pr changes most debug to info.
> [IMP] info: log level debug to info

- conftest.py
* try to improve ngrok setup / runner
* update github interface to automatically perform conditional requests when fetching PRs
the pr interface is convenient but it triggers a fetch on every access, which might be way unnecessary when repeatedly interacting with the same PR
> Improve mergebot test harness

- forwardport/models/project.py
Instead of "[FW]Create README.md", the forwardport PR is now named "[FW] Create README.md"
> [IMP] forwardport: add missing space

- runbot/controllers/frontend.py
- runbot/templates/build.xml
- runbot/templates/utils.xml
Quick prototype to find similar builds, especially usefull for nighlty
to list history of some subbuild.
> [IMP] runbot: add a build search page

- runbot/controllers/frontend.py
- runbot/models/batch.py
1. Log who started a manull build
2. redirect if the batch given in a build url is not containing this
build (manual url)
> [IMP] runbot: log manual batch and redirect

- runbot/models/repo.py
- runbot/views/repo_views.xml
This will be mainy usefull in trigger categories custom view and for
dashboards.
> [IMP] runbot: add teams on trigger.

- runbot/models/repo.py
- runbot/templates/batch.xml
- runbot/views/repo_views.xml
- dont display manual trigger having a team if not member of that team
- add an active field on triggers
> [IMP] runbot: active trigger and filter manual

- conftest.py
Forward-port support for no tunnel.
> [MERGE] from 14.0

- runbot/models/build_config.py
- runbot/models/version.py
- remove duplicate "Discover new commits" in README
- fix `additional_env` help message - the variables are split on semi-column (;) not comma (,)
- fix crash when trying to create a new `runbot.version` from the backend
> [FIX] runbot: various fixes

- runbot/models/host.py
If the db_name does not stat with a build ind (or at least an int) the query will fail because of 'local_pg_cursor'
Since a database can be create with an invalid name from the db manager but still log in the runbot_logs, we need to manage all format. Also add a limit to catchup if the db is full of logs, to avoid a Memory error.
Also removes the try except to get the error and not silence it.
> [FIX] runbot: fix invalid db_name log local

- runbot/templates/build.xml
- runbot/views/dashboard_views.xml
* Hide useless pages on backend team form
* Add a team exceptions page on team form
* Show fixed errors as fixed on front build page
> [IMP] runbot: improve team form and build frontend page

- runbot/__manifest__.py
- runbot/data/runbot_data.xml
- runbot/migrations/15.0.5.3/post-migration.py
- runbot/migrations/15.0.5.3/pre-migration.py
- runbot/models/branch.py
- runbot/models/codeowner.py
- runbot/models/project.py
- runbot/tests/test_branch.py
- runbot_populate/models/runbot.py
When adding a new project, if no branch matches a base name, the created bundles won't have a version and it will fail.
A simple fix will be to add a master bundle for all projects.
> [IMP] runbot: automatic base master bundle

- runbot/templates/nginx.xml
This will allow to ease to tests new configurations as it was needed for websockets, without risk to erase a customization on update
> [IMP] runbot: add some anchors in nginx

- runbot/controllers/frontend.py
- runbot/models/build_error.py
- runbot/static/src/js/fields.js
- runbot/tests/common.py
- runbot/tests/test_build.py
- runbot/views/build_error_views.xml
- runbot/views/bundle_views.xml
- runbot/views/host_views.xml
* add a link to the fixing PR on github
* add a warning ribbon on test-tagged errors
* show different colors in tree view to spot fixed PR's
* add some search filters
* improve the wizard to set a fixing PR and/or a commit text to multiple errors.
> 15.0 improve build errors moc

- runbot/data/runbot_data.xml
- runbot/models/build.py
- runbot/models/res_config_settings.py
- runbot/tests/test_upgrade.py
- runbot/views/res_config_settings_views.xml
Firefox blocks downloads from http link if you are on an https page
> [FIX] runbot: download over https

- runbot/models/host.py
- runbot_builder/tools.py
Pausing a host can be usefull in some case, mainly when testing new code The loop will have no effect avoiding to break some build wainting for testing.
Profile will help to identify potential performance flows during the loop.
> [IMP] runbot: pause, and profile.

- runbot/controllers/frontend.py
- runbot/models/batch.py
- runbot/models/build.py
- runbot/models/build_config.py
- runbot/models/res_users.py
- runbot/templates/build.xml
- runbot/templates/nginx.xml
- runbot/views/user.xml
- scan all build
- user view
- manual reference batch
- customizable build run access
- fix performance of many child build display
> [IMP] various fix and imps

- runbot/models/res_config_settings.py
- runbot/views/custom_trigger_wizard_views.xml
- runbot/views/res_config_settings_views.xml
The runbot settings view is a bit messy and the 16.0 upgrade added mess on the existing one.
This commit is an attempt to make it a bit clearer and cleaner.
> [REF] runbot: update settings view

- runbot/models/build_config.py
Manage multiple upgrade_paths + small fix
> [FIX] runbot: use upgrade path

- runbot/models/host.py
- runbot/views/host_views.xml
The main goal being to be able to reserve one host and highly increase the number of running build for special usage
> [IMP] runbot: allow to define a per host nb run

- runbot/models/commit.py
> [FIX] runbot: fix _get_commit_infos

- runbot/models/build_error.py
- runbot/tests/test_build_error.py
When a build that contains the same error that appears two times is parsed, it crashes because of the unique constraint on build error link.
With this commit, only one link with the same error is created. Two tests are added for the two cases:
-  a new error appearing two times in a same build
- an existing error appearing two times in a same build
> [FIX] runbot: allow build parsing with same error
